/* Browser-only exports: data never leaves the device to create a workbook/report. */
(() => {
 'use strict';
 const M=Lab7Math,loaders=new Map(),xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 function load(file){if(!loaders.has(file))loaders.set(file,new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='../assets/vendor/lab-export/'+file;s.onload=resolve;s.onerror=()=>{loaders.delete(file);s.remove();reject(Error('Export library could not load. Check your connection and retry.'));};document.head.append(s);}));return loaders.get(file);}
 const num=M.number;
 const formula=(cell,text,value)=>{cell.value={formula:text,result:value??''};};
 function style(sheet,columns){sheet.columns=columns.map((w,i)=>({key:'c'+i,width:w}));sheet.views=[{state:'frozen',ySplit:3}];sheet.pageSetup={paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0};}
 function input(cell,v){cell.value=num(v);cell.font={color:{argb:'FF195A9F'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF0F6FC'}};cell.numFmt='0.00000E+00';}
 const ref=(name,range)=>`'${name}'!${range}`;
 function cache(rows,key,total){return `<c:numCache><c:formatCode>General</c:formatCode><c:ptCount val="${total}"/>${rows.filter(p=>Number.isFinite(p[key])).map(p=>`<c:pt idx="${p.i}"><c:v>${p[key]}</c:v></c:pt>`).join('')}</c:numCache>`;}
 function numRef(form,rows,key,total){return `<c:numRef><c:f>${xml(form)}</c:f>${cache(rows,key,total)}</c:numRef>`;}
 function title(t){return `<c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US"/><a:t>${xml(t)}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title>`;}
 function chartXML(k,rows,total){
  const a=k==='A',name='Part '+k,last=total+3,x=a?'J':'K',y=a?'K':'L',dx=a?'C':'J',dy=a?'E':'F';
  const range=c=>ref(name,`$${c}$4:$${c}$${last}`);
  const err=(dir,col,key)=>`<c:errBars><c:errDir val="${dir}"/><c:errBarType val="both"/><c:errValType val="cust"/><c:noEndCap val="0"/><c:plus>${numRef(range(col),rows,key,total)}</c:plus><c:minus>${numRef(range(col),rows,key,total)}</c:minus></c:errBars>`;
  const axis=(id,cross,pos,label)=>`<c:valAx><c:axId val="${id}"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="${pos}"/><c:majorGridlines/>${title(label)}<c:numFmt formatCode="0.00E+00" sourceLinked="0"/><c:majorTickMark val="out"/><c:minorTickMark val="none"/><c:tickLblPos val="nextTo"/><c:crossAx val="${cross}"/><c:crosses val="autoZero"/><c:crossBetween val="midCat"/></c:valAx>`;
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><c:lang val="en-US"/><c:chart>${title('Part '+k+' — Resistance versus '+(a?'length':'inverse area'))}<c:plotArea><c:layout/><c:scatterChart><c:scatterStyle val="marker"/><c:ser><c:idx val="0"/><c:order val="0"/><c:tx><c:v>Measured resistance</c:v></c:tx><c:spPr><a:ln><a:noFill/></a:ln></c:spPr><c:marker><c:symbol val="circle"/><c:size val="5"/></c:marker><c:trendline><c:name>Least-squares fit</c:name><c:trendlineType val="linear"/><c:dispRSqr val="1"/><c:dispEq val="1"/></c:trendline>${err('x',dx,'dx')}${err('y',dy,'dy')}<c:xVal>${numRef(range(x),rows,'x',total)}</c:xVal><c:yVal>${numRef(range(y),rows,'y',total)}</c:yVal></c:ser><c:axId val="100"/><c:axId val="200"/></c:scatterChart>${axis(100,200,'b',a?'Length L (m)':'Inverse area 1/A (m⁻²)')}${axis(200,100,'l','Resistance R (Ω)')}</c:plotArea><c:plotVisOnly val="0"/><c:dispBlanksAs val="gap"/></c:chart></c:chartSpace>`;
 }
 async function addCharts(buffer,a,count){
  const zip=await JSZip.loadAsync(buffer),ns='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
  const anchor=(id,row)=>`<xdr:twoCellAnchor><xdr:from><xdr:col>0</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${row}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:to><xdr:col>11</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${row+21}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to><xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="${id+1}" name="Part ${id===1?'A':'B'} scatter chart"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></xdr:xfrm><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:r="${ns}" r:id="rId${id}"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:twoCellAnchor>`;
  zip.file('xl/drawings/drawing1.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">${anchor(1,3)}${anchor(2,26)}</xdr:wsDr>`);
  zip.file('xl/drawings/_rels/drawing1.xml.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${[1,2].map(i=>`<Relationship Id="rId${i}" Type="${ns}/chart" Target="../charts/chart${i}.xml"/>`).join('')}</Relationships>`);
  zip.file('xl/charts/chart1.xml',chartXML('A',a.A,19));zip.file('xl/charts/chart2.xml',chartXML('B',a.B,count));
  const sheet='xl/worksheets/sheet5.xml';zip.file(sheet,(await zip.file(sheet).async('string')).replace('</worksheet>','<drawing r:id="rIdLabCharts"/></worksheet>'));
  zip.file('xl/worksheets/_rels/sheet5.xml.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdLabCharts" Type="${ns}/drawing" Target="../drawings/drawing1.xml"/></Relationships>`);
  const types=await zip.file('[Content_Types].xml').async('string');zip.file('[Content_Types].xml',types.replace('</Types>',`<Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/>${[1,2].map(i=>`<Override PartName="/xl/charts/chart${i}.xml" ContentType="application/vnd.openxmlformats-officedocument.drawingml.chart+xml"/>`).join('')}</Types>`));
  return zip.generateAsync({type:'uint8array',compression:'DEFLATE'});
 }
 async function workbook(d){
  const a=M.analyze(d),w=new ExcelJS.Workbook();w.creator='Tesselate';w.title='PHYS 210 Experiment 7';w.calcProperties.fullCalcOnLoad=true;
  const setup=w.addWorksheet('Setup'),pa=w.addWorksheet('Part A'),pb=w.addWorksheet('Part B'),r=w.addWorksheet('Results'),graphs=w.addWorksheet('Graphs'),notes=w.addWorksheet('Report notes');
  style(setup,[36,72]);setup.addRow(['Experiment 7 — input settings']);setup.addRow(['Blue cells are editable inputs. Formulas and charts update when Excel recalculates.']);setup.mergeCells('A2:B2');setup.addRow(['Setting','Value']);
  const settings=[['Student',d.student],['Partners',d.partners],['Date',d.date],['Section',d.section],['Meter / range',d.meter],['Temperature (°C)',d.temperature],['Part A diameter (mm)',d.diameter],['Part A Δdiameter (mm)',d.dDiameter],['Part B length (m)',d.lengthB],['Part B Δlength (m)',d.dLengthB],['Accepted resistivity (Ω·m)',d.accepted],['Part A minimum slope (Ω/m)',d.aMin],['Part A maximum slope (Ω/m)',d.aMax],['Part B minimum slope (Ω·m²)',d.bMin],['Part B maximum slope (Ω·m²)',d.bMax]];
  settings.forEach(([label,v],i)=>{setup.getCell(i+4,1).value=label;if(i>=5)input(setup.getCell(i+4,2),v);else setup.getCell(i+4,2).value=v||null;});
  const headersA=['Point','L (m)','ΔL (m)','R (Ω)','ΔR (Ω)','Predicted R (Ω)','Residual (Ω)','','','Valid L (m)','Valid R (Ω)'];
  style(pa,[9,17,17,17,17,20,19,4,4,19,19]);pa.addRow(['Part A — fixed diameter']);pa.addRow(['Enter actual readings and uncertainties. Helpers exclude incomplete/non-positive length or resistance pairs from fitting.']);pa.mergeCells('A2:K2');pa.addRow(headersA);
  for(let i=0;i<19;i++){const row=i+4,p=a.A.find(p=>p.i===i);pa.getCell(row,1).value=i+1;['L','dL','R','dR'].forEach((k,j)=>input(pa.getCell(row,j+2),d['a'+i+k]));formula(pa.getCell('J'+row),`IF(AND(ISNUMBER(B${row}),B${row}>0,ISNUMBER(D${row}),D${row}>0),B${row},"")`,p?.x);formula(pa.getCell('K'+row),`IF(ISNUMBER(J${row}),D${row},"")`,p?.y);formula(pa.getCell('F'+row),`IF(AND(ISNUMBER(J${row}),ISNUMBER('Results'!B4)),J${row}*'Results'!B4+'Results'!B5,"")`,p&&a.af?a.af.m*p.x+a.af.b:null);formula(pa.getCell('G'+row),`IF(ISNUMBER(F${row}),K${row}-F${row},"")`,p&&a.af?p.y-a.af.m*p.x-a.af.b:null);}
  const count=Number(d.bCount)||6,last=count+3;
  style(pb,[9,10,17,17,16,17,19,19,19,19,19,19]);pb.addRow(['Part B — fixed length']);pb.addRow(['Diameters are entered in mm and converted to m in area formulas. Add further wires in the lab tool before exporting.']);pb.mergeCells('A2:L2');pb.addRow(['Wire','AWG','d (mm)','Δd (mm)','R (Ω)','ΔR (Ω)','Area (m²)','ΔArea (m²)','1/Area (m⁻²)','Δ(1/Area) (m⁻²)','Valid 1/A (m⁻²)','Valid R (Ω)']);
  for(let i=0;i<count;i++){const row=i+4,p=a.B.find(p=>p.i===i),dia=M.positive(d['b'+i+'d']),dd=M.nonnegative(d['b'+i+'dd']),ar=dia?M.area(dia):null,da=ar!==null&&dd!==null?2*ar*dd/dia:null;pb.getCell(row,1).value=i+1;['g','d','dd','R','dR'].forEach((k,j)=>input(pb.getCell(row,j+2),d['b'+i+k]));formula(pb.getCell('G'+row),`IF(AND(ISNUMBER(C${row}),C${row}>0),PI()*(C${row}/1000)^2/4,"")`,ar);formula(pb.getCell('H'+row),`IF(AND(ISNUMBER(G${row}),ISNUMBER(D${row}),D${row}>=0),2*G${row}*D${row}/C${row},"")`,da);formula(pb.getCell('I'+row),`IF(ISNUMBER(G${row}),1/G${row},"")`,ar?1/ar:null);formula(pb.getCell('J'+row),`IF(ISNUMBER(H${row}),H${row}/G${row}^2,"")`,da!==null?da/ar**2:null);formula(pb.getCell('K'+row),`IF(AND(ISNUMBER(I${row}),ISNUMBER(E${row}),E${row}>0),I${row},"")`,p?.x);formula(pb.getCell('L'+row),`IF(ISNUMBER(K${row}),E${row},"")`,p?.y);}
  style(r,[39,25,24]);r.addRow(['Resistivity calculations']);r.addRow(['Conservative uncertainty sums. Minimum/maximum slopes must be positive, different and bracket the best fit.']);r.mergeCells('A2:C2');r.addRow(['Quantity','Value','Unit']);
  function res(row,label,f,value,unit){r.getCell(row,1).value=label;formula(r.getCell(row,2),f,value);r.getCell(row,3).value=unit;r.getCell(row,2).numFmt='0.00000E+00';}
  function fitRows(start,sheet,x,y,end,f){const xr=ref(sheet,`${x}4:${x}${end}`),yr=ref(sheet,`${y}4:${y}${end}`),guard=`AND(COUNT(${yr})>=3,DEVSQ(${xr})>0)`;res(start,'Part '+(start===4?'A':'B')+' best-fit slope',`IF(${guard},SLOPE(${yr},${xr}),"")`,f?.m,start===4?'Ω/m':'Ω·m²');res(start+1,'Intercept',`IF(ISNUMBER(B${start}),INTERCEPT(${yr},${xr}),"")`,f?.b,'Ω');res(start+2,'R squared',`IF(AND(ISNUMBER(B${start}),DEVSQ(${yr})>0),RSQ(${yr},${xr}),"")`,f?.r2,'');}
  fitRows(4,'Part A','J','K',22,a.af);fitRows(8,'Part B','K','L',last,a.bf);
  res(12,'Part A cross-sectional area',`IF(AND(ISNUMBER('Setup'!B10),'Setup'!B10>0),PI()*('Setup'!B10/1000)^2/4,"")`,a.areaA,'m²');res(13,'Part A area uncertainty',`IF(AND(ISNUMBER(B12),ISNUMBER('Setup'!B11),'Setup'!B11>=0),2*B12*'Setup'!B11/'Setup'!B10,"")`,a.dAreaA,'m²');
  for(const [row,source,label,unit] of [[15,15,'Part A minimum slope','Ω/m'],[16,16,'Part A maximum slope','Ω/m'],[21,17,'Part B minimum slope','Ω·m²'],[22,18,'Part B maximum slope','Ω·m²'],[31,14,'Accepted resistivity','Ω·m']])res(row,label,`IF(AND(ISNUMBER('Setup'!B${source}),'Setup'!B${source}>0),'Setup'!B${source},"")`,M.positive(d[{15:'aMin',16:'aMax',17:'bMin',18:'bMax',14:'accepted'}[source]]),unit);
  res(17,'Part A slope uncertainty','IF(AND(ISNUMBER(B4),ISNUMBER(B15),ISNUMBER(B16),B15<=B4,B16>=B4,B16>B15),(B16-B15)/2,"")',a.au?.dm,'Ω/m');
  res(18,'Part A resistivity','IF(AND(ISNUMBER(B4),B4>0,ISNUMBER(B12)),B4*B12,"")',a.rhoA,'Ω·m');
  res(19,'Part A resistivity uncertainty','IF(AND(ISNUMBER(B18),ISNUMBER(B17),ISNUMBER(B13)),B18*(B17/B4+B13/B12),"")',a.drhoA,'Ω·m');
  res(23,'Part B slope uncertainty','IF(AND(ISNUMBER(B8),ISNUMBER(B21),ISNUMBER(B22),B21<=B8,B22>=B8,B22>B21),(B22-B21)/2,"")',a.bu?.dm,'Ω·m²');
  res(24,'Part B resistivity',`IF(AND(ISNUMBER(B8),B8>0,ISNUMBER('Setup'!B12),'Setup'!B12>0),B8/'Setup'!B12,"")`,a.rhoB,'Ω·m');
  res(25,'Part B resistivity uncertainty',`IF(AND(ISNUMBER(B24),ISNUMBER(B23),ISNUMBER('Setup'!B13),'Setup'!B13>=0),B24*(B23/B8+'Setup'!B13/'Setup'!B12),"")`,a.drhoB,'Ω·m');
  res(27,'Absolute difference','IF(AND(ISNUMBER(B18),ISNUMBER(B24)),ABS(B18-B24),"")',a.difference,'Ω·m');res(28,'Sum of uncertainties','IF(AND(ISNUMBER(B19),ISNUMBER(B25)),B19+B25,"")',a.combined,'Ω·m');res(29,'Consistent (strict inequality)','IF(AND(ISNUMBER(B27),ISNUMBER(B28)),IF(B27<B28,"Consistent","Not consistent"),"Awaiting inputs")',a.consistent===null?'Awaiting inputs':a.consistent?'Consistent':'Not consistent','');
  res(32,'Part A absolute percent difference','IF(AND(ISNUMBER(B18),ISNUMBER(B31)),ABS(B18-B31)/B31,"")',a.percentA===null?null:a.percentA/100,'');r.getCell('B32').numFmt='0.00%';res(33,'Part B absolute percent difference','IF(AND(ISNUMBER(B24),ISNUMBER(B31)),ABS(B24-B31)/B31,"")',a.percentB===null?null:a.percentB/100,'');r.getCell('B33').numFmt='0.00%';
  style(graphs,Array(11).fill(11));graphs.addRow(['Experiment 7 — editable Excel charts']);graphs.mergeCells('A1:K1');graphs.addRow(['Native scatter plots with custom x/y error bars and least-squares trendlines. Charts recalculate from the measurement sheets.']);graphs.mergeCells('A2:K2');
  style(notes,[34,110]);notes.addRow(['Report notes and completeness at export']);notes.addRow([a.complete?'Required fields filled — review before submission':'DRAFT — missing or unresolved inputs']);notes.mergeCells('A2:B2');notes.addRow(['Section','Text']);for(const [h,t] of [['Missing at export',a.issues.join('\n')||'None'],['Uncertainty method',d.uncertaintyNotes],['Slope-limit method',d.slopeNotes],['Actual observations',d.observations],['Discussion',d.discussion],['Conclusion',d.conclusion],['Accepted-value reference',d.acceptedSource],['Manual source','PHYS 210 Lab Manual Complete 2024, L7-1–L7-4 (PDF pp. 101–104). https://online.camosun.ca/d2l/le/content/348967/viewContent/5448840/View']]){const row=notes.addRow([h,t||'Not entered']);row.alignment={wrapText:true,vertical:'top'};row.height=Math.min(240,Math.max(45,Math.ceil((t||'').length/100)*16));}
  for(const s of [pa,pb]){for(let row=4;row<=s.rowCount;row++)s.getRow(row).eachCell(cell=>{if(cell.col>1)cell.numFmt='0.00000E+00';});s.autoFilter={from:'A3',to:{row:s.rowCount,column:s.columnCount}};}for(let row=4;row<=pb.rowCount;row++)pb.getCell(row,2).numFmt='0'; r.pageSetup.orientation='portrait'; r.pageSetup.fitToHeight=1; pa.getColumn(10).hidden=true;pa.getColumn(11).hidden=true;pb.getColumn(11).hidden=true;pb.getColumn(12).hidden=true;
  for(const sheet of w.worksheets){sheet.getRow(1).font={bold:true,size:18,color:{argb:'FF176B65'}};sheet.getRow(1).height=30;sheet.getRow(2).height=40;sheet.getRow(2).alignment={wrapText:true,vertical:'top'};sheet.getRow(3).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(3).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF176B65'}};sheet.getRow(3).height=38;sheet.getRow(3).alignment={wrapText:true,vertical:'middle'};}
  return addCharts(await w.xlsx.writeBuffer(),a,count);
 }
 async function png(svg){
  const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;});const c=document.createElement('canvas');c.width=1400;c.height=Math.round(1400*img.naturalHeight/img.naturalWidth);const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));return new Uint8Array(await blob.arrayBuffer());}finally{URL.revokeObjectURL(url);}
 }
 async function report(model){
  const {Document,Packer,Paragraph,TextRun,HeadingLevel,Table,TableRow,TableCell,WidthType,ImageRun}=docx;
  const text=(s,opts={})=>new Paragraph({...opts,children:String(s).split('\n').flatMap((line,i)=>[...(i?[new TextRun({break:1})]:[]),new TextRun(line)])});
  const children=[text(model.title,{heading:HeadingLevel.TITLE}),text(model.subtitle),...(model.partners?[text('Partners: '+model.partners)]:[])];
  if(!model.a.complete){children.push(text('DRAFT — missing or unresolved inputs',{heading:HeadingLevel.HEADING_2}));for(const issue of model.a.issues)children.push(text(issue,{bullet:{level:0}}));}
  for(let i=0;i<model.sections.length;i++){
   const [h,p]=model.sections[i];children.push(text((i+1)+'. '+h,{heading:HeadingLevel.HEADING_1}),text(p));
   if(i===3)for(const f of model.figures||[]){const response=await fetch(f.src);if(!response.ok)throw new Error('Could not load procedure diagram');children.push(new Paragraph({keepNext:true,children:[new ImageRun({type:'png',data:await png(await response.text()),transformation:{width:540,height:324},altText:{title:f.caption,description:f.caption,name:'Procedure diagram'}})]}),new Paragraph({children:[new TextRun({text:f.caption,italics:true,size:20})]}));}
   if(i===4)for(const t of model.tables){children.push(text(t.title,{heading:HeadingLevel.HEADING_2}));children.push(new Table({borders:Object.fromEntries(["top","bottom","left","right","insideHorizontal","insideVertical"].map(k=>[k,{style:"single",size:4,color:"D9D9D9"}])),width:{size:100,type:WidthType.PERCENTAGE},rows:[t.headers,...t.rows].map((row,ri)=>new TableRow({tableHeader:ri===0,cantSplit:true,children:row.map(v=>new TableCell({shading:ri===0?{fill:'E5F0ED'}:undefined,children:[new Paragraph({spacing:{after:40,before:40},children:[new TextRun({text:String(v),bold:ri===0,size:18})]})]}))}))}));}
   if(i===5)for(const svg of model.charts)if(svg.startsWith('<svg'))children.push(new Paragraph({children:[new ImageRun({type:'png',data:await png(svg),transformation:{width:540,height:270},altText:{title:'Experiment 7 measurement graph',description:'Measured points, uncertainty bars and best-fit line',name:'Measurement graph'}})]}));
  }
  return Packer.toBlob(new Document({creator:'Tesselate',title:model.title,styles:{paragraphStyles:[{id:'Title',name:'Title',basedOn:'Normal',run:{font:'Times New Roman',size:40,bold:true,color:'202D35'}},{id:'Heading1',name:'Heading 1',basedOn:'Normal',next:'Normal',run:{font:'Times New Roman',size:28,bold:true,color:'202D35'},paragraph:{keepNext:true,spacing:{before:240,after:120}}},{id:'Heading2',name:'Heading 2',basedOn:'Normal',next:'Normal',run:{font:'Times New Roman',size:24,bold:true,color:'202D35'},paragraph:{keepNext:true}}],default:{document:{run:{font:'Times New Roman',size:24},paragraph:{spacing:{after:110,line:264}}}}},sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:850,bottom:850,left:850,right:850}}},children}]}));
 }
 async function run(kind){const status=document.getElementById('exportStatus'),button=document.getElementById(kind);button.disabled=true;status.textContent='Preparing '+(kind==='excel'?'Excel workbook':'Word report')+'…';try{if(kind==='excel'){await Promise.all([load('exceljs.min.js'),load('jszip.min.js')]);const bytes=await workbook(Lab7UI.getData());Lab7UI.download(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'phys210-experiment7.xlsx');}else{await load('docx.js');Lab7UI.download(await report(Lab7UI.reportModel()),'phys210-experiment7-report.docx');}status.textContent='Download ready. '+(Lab7UI.reportModel().a.complete?'Review the file before submitting.':'This is a draft; missing inputs are listed above.');}catch(e){status.textContent='Export failed: '+e.message+'. Your readings remain saved; try again.';}finally{button.disabled=false;}}
 document.getElementById('excel').onclick=()=>run('excel');document.getElementById('word').onclick=()=>run('word');
 window.Lab7Export={workbook,report,chartXML};
})();
