/* Rebuild Math 252's source library from the checked-in material manifest. */
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.join(root,'math252');
const materials=require('../math252/materials.json');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pdfs=materials.filter(m=>m.downloaded),pages=pdfs.reduce((n,m)=>n+m.pages,0);
function card(m){return `<article class="material" data-search="${esc(m.title.toLowerCase())}"><div><span class="eyebrow">${m.downloaded?`PDF · ${m.pages} page${m.pages===1?'':'s'}`:m.localPath?'IMAGE':'EXTERNAL RESOURCE'}</span><h3>${esc(m.title)}</h3></div><div class="actions">${m.downloaded?`<a class="button" href="pdfs/${esc(m.filename)}">Open PDF</a><a href="pdfs/${esc(m.filename)}" download>Download</a>`:m.localPath?`<a class="button" href="${esc(m.localPath)}">Open image</a>`:''}<a href="${esc(m.url)}" target="_blank" rel="noopener">${m.downloaded?'Instructor’s original':'Open resource'} ↗</a></div></article>`;}
const groups=['Coursework','Course notes','Handouts and review','Videos and further reading'];
const sections=groups.map((group,i)=>`<section id="group-${i}" class="material-group"><h2>${group}</h2>${group==='Coursework'?'<p>The suggested textbook problems link uses the 10th edition; the notes page lists the 11th edition. Check the edition before matching exercise numbers.</p>':''}${materials.filter(m=>m.category===group).map(card).join('\n')}</section>`).join('\n');
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Math 252 · Applied Differential Equations · Tesselate</title><link rel="stylesheet" href="../engr290/course.css"><link rel="stylesheet" href="course.css"><script defer src="../engr290/theme.js"></script><script defer src="library.js"></script></head>
<body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="../index.html#course/math252">tesselate<span>.</span></a><nav aria-label="Course navigation"><a href="#study-map">Study map</a><a href="#library">Materials</a><button id="theme" type="button" aria-label="Toggle dark appearance">◐</button></nav></header>
<main id="main"><p class="eyebrow">MATH 252 / FALL 2026</p><h1>Applied Differential Equations</h1><p class="lead">Your complete course library, from first-order equations to Laplace transforms and linear systems.</p><p>Gilles Cazelais · Camosun College</p><div class="notice"><strong>${pdfs.length} PDFs · ${pages} pages · 1 graph image · ${materials.filter(m=>!m.localPath).length} supporting links</strong><p>Course notes, the outline, Assignment 1, practice questions and solutions, formula sheets, and review handouts. Collected September 22, 2026; check the instructor’s page for later additions and schedule changes.</p></div><div class="actions"><a class="button primary" href="#library">Browse all materials ↓</a><a class="button" href="https://sites.google.com/site/cazelais/home/math252" target="_blank" rel="noopener">Instructor’s course page ↗</a></div>
<section id="study-map"><h2>A map of the course</h2><p>Use this topic guide to choose where to begin, then work through the corresponding notes and exercises.</p><div class="grid"><div><h3>1 · First-order equations</h3><p>Sections 1.1–3.1. Identify the equation’s form before choosing separation, an integrating factor, exactness, or substitution. Use an initial condition to determine the constant.</p></div><div><h3>2 · Higher-order equations</h3><p>Sections 4.1–5.1. Build the homogeneous solution, find a particular solution when needed, and apply initial conditions. Connect the result to mechanical motion and circuits.</p></div><div><h3>3 · Power series</h3><p>Sections 6.1–6.2. Express the unknown solution as a series, align powers, and compare coefficients to obtain a recurrence.</p></div><div><h3>4 · Laplace transforms</h3><p>Sections 7.1–7.5. Transform an initial-value problem into algebra, solve for the transformed function, and invert it. Review partial fractions and shifting properties.</p></div><div><h3>5 · Linear systems</h3><p>Sections 8.1–8.3. Write coupled equations in matrix form and use eigenvalues and eigenvectors to construct solutions. Account for forcing in nonhomogeneous systems.</p></div></div></section>
<div id="library"><h2>Course materials</h2><label for="search">Find a topic or resource</label><input id="search" type="search" placeholder="Try Laplace, Section 2.3, or solutions" aria-describedby="result-count"><p id="result-count" role="status">${materials.length} resources</p><nav aria-label="Material categories">${groups.map((g,i)=>`<a href="#group-${i}">${g}</a>`).join('')}</nav></div>
${sections}<p id="no-results" hidden>No matching materials. Try a section number or a shorter topic name.</p>
<section class="sources"><h2>Sources and updates</h2><p>Original course materials remain attributed to their authors. PDFs are preserved as downloaded; the study map above is a Tesselate guide.</p><ul><li><a href="https://sites.google.com/site/cazelais/home/math252">Instructor’s course page</a></li><li><a href="https://sites.google.com/site/cazelais/home/math252/notes">Course notes and supplemental resources</a></li><li><a href="https://sites.google.com/site/cazelais/home/math252/homework">Suggested textbook problems</a></li></ul><p>The periodic-function supplement is marked by the instructor as not tested and intended for electronics students. Videos and other web resources open at their original sites.</p></section></main><footer><a href="../index.html#course/math252">← MATH 252 workspace</a><p>Collected from Gilles Cazelais’s public course pages on September 22, 2026.</p></footer></body></html>`;
fs.writeFileSync(path.join(out,'review.html'),html);
console.log(`Math 252 library: ${materials.length} resources, ${pdfs.length} PDFs, ${pages} pages.`);
