// Rebuild static lessons and the browser question bank after editing content.json.
const fs = require('node:fs');
const path = require('node:path');
const dir = path.join(__dirname, '../engr290');
const data = require('../engr290/content.json');
const esc = s => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const sources = names => `<ul>${names.map(s=>`<li><a href="../ENGR%20290/${encodeURIComponent(s)}">${esc(s)}</a></li>`).join('')}</ul>`;
const shell = (title,body,scripts='') => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · ENGR 290</title><link rel="stylesheet" href="course.css"><script defer src="theme.js"></script>${scripts}</head>
<body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="../index.html#course/engr290">tesselate<span>.</span></a><nav aria-label="Course navigation"><a href="review.html">Lessons</a><a href="quiz.html">Quiz</a><a href="exam.html">Practice test</a><button id="theme" type="button" aria-label="Toggle dark appearance">◐</button></nav></header><main id="main"><p class="eyebrow">ENGR 290 / FALL 2026</p>${body}</main><footer><a href="../index.html#course/engr290">← Engineering Materials workspace</a><p>Original study aids based on your supplied course materials.</p></footer></body></html>`;
for (let i=0;i<data.lessons.length;i++) {
 const l=data.lessons[i];
 fs.writeFileSync(path.join(dir,l.slug+'.html'),shell(l.title,`<a href="review.html">← All lessons</a><h1>${esc(l.title)}</h1><p class="lead">${esc(l.summary)}</p>${l.sections.map(s=>`<section><h2>${esc(s.title)}</h2><p>${esc(s.body)}</p></section>`).join('')}<section class="worked"><p class="eyebrow">WORKED EXAMPLE</p><p>${esc(l.example)}</p></section><section><h2>Check your understanding</h2><p>${esc(l.check)}</p><details><summary>Show the worked answer</summary><p>${esc(l.answer)}</p></details></section><div class="actions"><a class="button primary" href="quiz.html?topic=${i}">Practise this topic →</a>${data.lessons[i+1]?`<a class="button" href="${data.lessons[i+1].slug}.html">Next lesson →</a>`:''}</div><section class="sources"><h2>Course sources</h2>${sources(l.sources)}${i===4?'<p>Supplement: <a href="https://ocw.mit.edu/courses/3-091sc-introduction-to-solid-state-chemistry-fall-2010/pages/reactions-and-kinetics/24-diffusion/">MIT OpenCourseWare diffusion lesson</a>.</p>':''}</section>`));
}
fs.writeFileSync(path.join(dir,'review.html'),shell('Lessons and review',`<h1>Engineering Materials</h1><p class="lead">Build the concepts. Work the numbers. Check what sticks.</p><div class="notice"><strong>Current coverage: opening materials units.</strong> These five lessons follow the Week 1 and Week 2 slides, with diffusion practice drawn from Assignment 1. Polymers, phase diagrams, and thermodynamics appear later in the outline and are not covered by this practice bank. The two supplied schedules differ, so confirm assessment dates with your instructor.</div><div class="actions"><a class="button primary" href="quiz.html">Start a quiz →</a><a class="button" href="exam.html">Take a practice test</a></div><div class="grid">${data.lessons.map(l=>`<a class="lesson-card" href="${l.slug}.html"><span class="eyebrow">LESSON</span><h2>${esc(l.title)}</h2><p>${esc(l.summary)}</p><span>Read lesson →</span></a>`).join('')}</div><section><h2>Calculation checklist</h2><ul><li>Convert length units before squaring or cubing.</li><li>Use kelvin in exponential temperature relations.</li><li>Distinguish directions [uvw] from planes (hkl).</li><li>Write assumptions, substitute values, and check the physical trend.</li></ul></section><section class="sources"><h2>Your original materials</h2>${sources(data.sources)}</section>`));
for(const mode of ['quiz','exam']) {
 const exam=mode==='exam';
 fs.writeFileSync(path.join(dir,mode+'.html'),shell(exam?'Practice test':'Practice quiz',`<h1>${exam?'Materials practice test':'Practise by topic'}</h1><p class="lead">${exam?'15 questions · 30 minutes · explanations after submission':'Choose a topic, check each answer, and learn from the explanation.'}</p><p>Practice covers the five opening materials lessons. These are study questions, not an official or full-course exam.</p><section id="setup"><label for="topic">Topic</label><select id="topic"><option value="all">All materials topics</option>${data.lessons.map((l,i)=>`<option value="${i}">${esc(l.title)}</option>`).join('')}</select><p>${exam?'The test samples three questions per topic when you choose all topics. A single-topic test uses all six questions from that topic. Unanswered questions count as incorrect. The timer starts when you begin.':'Each topic has six questions. All topics gives ten questions, balanced across the five lessons. Answers are saved on this device as you work.'}</p><button class="primary" id="start">${exam?'Start test':'Start quiz'}</button><button id="resume" hidden>Resume saved attempt</button><p id="storage-note" role="status"></p></section><section id="session" hidden></section><section id="results" hidden tabindex="-1"></section><noscript><p>Enable JavaScript for interactive practice. <a href="review.html">The lessons and worked examples are available without JavaScript.</a></p></noscript>`,`<script defer src="bank.js"></script><script defer src="practice.js"></script>`));
}
fs.writeFileSync(path.join(dir,'bank.js'),'window.ENGR290 = '+JSON.stringify(data)+';\n');
console.log('Built 5 lessons, review, quiz, and practice test.');
