// Authoring source. Use String.raw so TeX backslashes remain intact.
const r=String.raw;
const lessons=[],questions=[];
const A=n=>`250B-A${n}-2025F.pdf`, T=n=>`250BX01-T${n}Sol-2025F.pdf`, F='250B-formulasheet.pdf';
function lesson(slug,title,summary,sources,sections,example,check,answer){lessons.push({slug,title,summary,sources,sections:sections.map(([title,body])=>({title,body})),example,check,answer});}
lesson('01-partial-derivatives','01 · Surfaces and partial derivatives','Read a surface, differentiate one variable at a time, and follow the multivariable chain rule.',[A(1),T(1)],[
 ['Recognize the geometry',r`A graph \(z=f(x,y)\) assigns height to a point in the plane. The surface \(z=x^2+y^2\) is an upward-opening paraboloid. The equation \(x^2+y^2+z^2=9\) is a sphere of radius 3, while \(z=\sqrt{x^2+y^2}\) describes only the upper half of a circular cone. Fixing one coordinate gives a trace that helps identify the shape.`],
 ['Hold the other variables constant',r`In \(f_x\), differentiate with respect to \(x\) while holding \(y\) fixed. Ordinary product, quotient, and chain rules still apply. For \(f=x^2y+\ln(x+y)\), with \(x+y>0\): \[\frac{\partial f}{\partial x}=2xy+\frac{1}{x+y},\qquad \frac{\partial f}{\partial y}=x^2+\frac{1}{x+y}.\] A term depending only on the other variable differentiates to zero.`],
 ['Differentiate again',r`The mixed partial \(f_{xy}\) means differentiate \(f_x\) with respect to \(y\). For the previous example, \[f_{xy}=2x-\frac{1}{(x+y)^2}.\] When the mixed partials are continuous in a neighbourhood, \(f_{xy}=f_{yx}\). This is a useful check on your algebra.`],
 ['Follow every dependency',r`If \(z=f(u,v)\), with \(u=u(t)\) and \(v=v(t)\), both routes from \(t\) to \(z\) contribute: \[\frac{dz}{dt}=\frac{\partial f}{\partial u}\frac{du}{dt}+\frac{\partial f}{\partial v}\frac{dv}{dt}.\] Evaluate the inner variables at the requested point before substituting into the outer derivatives.`]
],r`Let \(z=u^2+3uv\), \(u=t^2\), and \(v=1+t\). At \(t=1\), \((u,v)=(1,2)\), so \(f_u=2u+3v=8\) and \(f_v=3u=3\). Therefore \[\left.\frac{dz}{dt}\right|_{t=1}=8(2)+3(1)=19.\] Directly substituting \(z=t^4+3t^2+3t^3\) and differentiating gives the same result.`,
r`For \(f(x,y)=\frac{x^2}{y}+\sin(xy)\), where \(y\ne0\), find both first partial derivatives.`,
r`Hold the other variable fixed and apply the chain rule: \[f_x=\frac{2x}{y}+y\cos(xy),\qquad f_y=-\frac{x^2}{y^2}+x\cos(xy).\]`);
lesson('02-gradients','02 · Tangent planes, gradients, and error','Use derivatives to approximate a surface and measure change in a chosen direction.',[A(1),A(2),T(1),T(2)],[
 ['Build a tangent plane',r`At a differentiable point \((a,b,f(a,b))\), the tangent plane is \[z=f(a,b)+f_x(a,b)(x-a)+f_y(a,b)(y-b).\] It is also the linear approximation \(L(x,y)\). A horizontal tangent plane requires both \(f_x=0\) and \(f_y=0\). For an implicit surface \(G(x,y,z)=c\), a nonzero gradient \(\nabla G\) is a normal vector.`],
 ['Normalize the direction',r`The gradient \(\nabla f=\langle f_x,f_y\rangle\) points toward fastest local increase when it is nonzero. For direction vector \(\mathbf v\), first form a unit vector, then take a dot product: \[\mathbf u=\frac{\mathbf v}{\|\mathbf v\|},\qquad D_{\mathbf u}f=\nabla f\cdot\mathbf u.\] The maximum directional derivative is \(\|\nabla f\|\), not the sum of its components.`],
 ['Approximate changes and errors',r`For small input changes, \(\Delta f\approx df=f_x\,dx+f_y\,dy\). When \(f=Cx^a y^b\) is nonzero and the inputs are positive, \[\frac{df}{f}=a\frac{dx}{x}+b\frac{dy}{y}.\] A first-order worst-case relative-error estimate adds absolute contributions. It is an approximation; it does not account for higher-order terms.`],
 ['Find a tangent to an intersection',r`For two level surfaces \(G=c_1\) and \(H=c_2\), a tangent direction at a regular intersection is \(\nabla G\times\nabla H\). Check that the point lies on both surfaces. If this cross product vanishes, the method does not supply a nonzero tangent direction.`]
],r`For \(f=x^2+xy\) at \((1,2)\), \(f=3\) and \(\nabla f=\langle4,1\rangle\). The tangent plane is \[z=3+4(x-1)+(y-2).\] In the direction \(\langle3,4\rangle\), use \(\mathbf u=\langle\frac35,\frac45\rangle\). Thus \[D_{\mathbf u}f=4\left(\frac35\right)+\frac45=\frac{16}{5}.\]`,
r`For \(f=\frac{x^2}{y}\), positive inputs have maximum relative errors 1% in \(x\) and 2% in \(y\). Estimate the maximum relative error in \(f\).`,
r`Here \(\frac{df}{f}=2\frac{dx}{x}-\frac{dy}{y}\). The worst-case magnitude is approximately \(2(1\%)+2\%=4\%\). Choose opposing input-error signs to make the contributions reinforce each other.`);
lesson('03-optimization','03 · Optimization and constraints','Classify critical points, check boundaries, and solve Lagrange multiplier equations.',[A(1),A(2),T(1),T(2),F],[
 ['Find all candidates',r`For a differentiable function on an open region, interior extrema require \(f_x=f_y=0\). Solve these equations together. Critical points can also occur where a partial derivative does not exist. A stationary point is a candidate, not a guarantee of a maximum or minimum.`],
 ['Use the second derivative test',r`At a stationary point, compute \[D=f_{xx}f_{yy}-(f_{xy})^2.\] With continuous second partials, \(D>0\) and \(f_{xx}>0\) imply a local minimum; \(D>0\) and \(f_{xx}<0\) imply a local maximum. If \(D<0\), the point is a saddle. If \(D=0\), this test is inconclusive.`],
 ['Absolute extrema require boundary checks',r`A continuous function on a closed, bounded region attains an absolute maximum and minimum. Compare function values at interior critical points, critical points along each boundary segment, and corners or endpoints. Substitute each boundary equation into \(f\) to reduce that part to one variable.`],
 ['Add the constraint equation',r`For a regular constraint \(g(x,y)=c\), solve \[\nabla f=\lambda\nabla g,\qquad g=c.\] Include every real solution and compare objective values. Check separately any constraint points where \(\nabla g=0\), plus endpoints or other restrictions. Dividing by a variable can accidentally discard a zero-valued candidate.`]
],r`Minimize \(f=x^2+y^2\) subject to \(x+2y=5\). The multiplier equations give \(2x=\lambda\) and \(2y=2\lambda\), hence \(y=2x\). Substituting into the constraint gives \((x,y)=(1,2)\), with \(f=5\). This is the absolute minimum because \[f(x,\tfrac{5-x}{2})=\frac54(x-1)^2+5.\] There is no maximum on this unbounded line.`,
r`Classify the critical point of \(f=x^2+2y^2-2x+8y\).`,
r`Solving \(2x-2=0\) and \(4y+8=0\) gives \((1,-2)\). Since \(D=2(4)-0=8>0\) and \(f_{xx}=2>0\), it is a local minimum. Completing squares gives \(f=(x-1)^2+2(y+2)^2-9\), proving the absolute minimum value is \(-9\).`);
lesson('04-double-integrals','04 · Double integrals and polar coordinates','Describe a region, choose an integration order, and compute area, volume, or mass.',[A(2),T(2),F],[
 ['Bounds describe slices',r`For vertical slices with \(a\le x\le b\) and \(g_1(x)\le y\le g_2(x)\), write \[\iint_R f\,dA=\int_a^b\int_{g_1(x)}^{g_2(x)}f(x,y)\,dy\,dx.\] Integrate the inner variable first. Horizontal slices reverse these roles. Sketch the region and identify intersections before choosing bounds.`],
 ['Reverse order by rebuilding the region',r`The region \(0\le x\le1\), \(x^2\le y\le1\) can also be described as \(0\le y\le1\), \(0\le x\le\sqrt y\). Thus \[\int_0^1\int_{x^2}^1 f\,dy\,dx=\int_0^1\int_0^{\sqrt y}f\,dx\,dy.\] Changing the order means changing the bounds, not just swapping the differential symbols.`],
 ['Use polar coordinates for circular geometry',r`Set \(x=r\cos\theta\), \(y=r\sin\theta\), and replace the area element by \(dA=r\,dr\,d\theta\). The extra \(r\) is essential. A disk of radius \(a\) uses \(0\le r\le a\) and \(0\le\theta\le2\pi\). A quarter disk in the first quadrant uses \(0\le\theta\le\frac\pi2\).`],
 ['Choose the physical integrand',r`Area uses integrand 1. Volume between surfaces uses top minus bottom. For a lamina with density \(\delta\), \[m=\iint_R\delta\,dA,\qquad \bar x=\frac{1}{m}\iint_R x\delta\,dA,\qquad \bar y=\frac{1}{m}\iint_R y\delta\,dA.\] The moments of inertia are \(I_x=\iint_R y^2\delta\,dA\) and \(I_y=\iint_R x^2\delta\,dA\); the squared coordinate measures distance from the named axis.`]
],r`Integrate \(x+y\) over \(0\le x\le1\), \(0\le y\le x\): \[\int_0^1\int_0^x(x+y)\,dy\,dx=\int_0^1\frac{3x^2}{2}\,dx=\frac12.\] For a separate polar example, over the disk \(x^2+y^2\le4\), \[\iint_R(x^2+y^2)\,dA=\int_0^{2\pi}\int_0^2r^3\,dr\,d\theta=8\pi.\]`,
r`Find the area between \(y=x^2\) and \(y=x\), from \(x=0\) to \(x=1\).`,
r`The upper curve is \(y=x\): \[A=\int_0^1\int_{x^2}^x1\,dy\,dx=\int_0^1(x-x^2)\,dx=\frac12-\frac13=\frac16.\]`);
lesson('05-triple-integrals','05 · Triple integrals and spherical coordinates','Translate three-dimensional boundaries into Cartesian, cylindrical, or spherical bounds.',[A(3),T(2),T(3),F],[
 ['Start with a solid and a projection',r`With lower and upper surfaces \(z_1(x,y)\) and \(z_2(x,y)\), describe their projection \(R\) onto the plane, then write \[\iiint_Q f\,dV=\iint_R\int_{z_1}^{z_2}f(x,y,z)\,dz\,dA.\] Volume uses \(f=1\); mass uses density. Verify lower and upper bounds throughout the projection.`],
 ['Cylindrical coordinates retain height',r`For axial symmetry use \[x=r\cos\theta,\quad y=r\sin\theta,\quad z=z,\qquad dV=r\,dz\,dr\,d\theta.\] The cone \(z=\sqrt{x^2+y^2}\) becomes \(z=r\). An integrand \(\sqrt{x^2+y^2}\) also becomes \(r\), so with the volume element it contributes \(r^2\), not just \(r\).`],
 ['Spherical angles have a convention',r`Here \(\phi\) is measured down from the positive vertical axis and \(\theta\) rotates around it: \[x=\rho\sin\phi\cos\theta,\quad y=\rho\sin\phi\sin\theta,\quad z=\rho\cos\phi.\] The volume element is \[dV=\rho^2\sin\phi\,d\rho\,d\phi\,d\theta.\] For a full ball, \(0\le\phi\le\pi\); for its upper hemisphere, \(0\le\phi\le\frac\pi2\).`],
 ['Translate every boundary and integrand',r`A sphere centred at the origin gives a constant \(\rho\). A plane \(z=c>0\) gives \(\rho=\frac{c}{\cos\phi}\) where \(\cos\phi>0\). The cone \(z=r\) gives \(\phi=\frac\pi4\). Also \(x^2+y^2=\rho^2\sin^2\phi\), whereas \(x^2+y^2+z^2=\rho^2\). Keep these two expressions distinct.`]
],r`The volume inside the ball \(\rho\le2\) and above the cone \(z=r\) is \[V=\int_0^{2\pi}\int_0^{\pi/4}\int_0^2\rho^2\sin\phi\,d\rho\,d\phi\,d\theta.\] Integrating gives \[V=2\pi\left(1-\frac{\sqrt2}{2}\right)\frac83=\frac{16\pi}{3}\left(1-\frac{\sqrt2}{2}\right).\] The answer is smaller than the volume of the upper hemisphere, as expected.`,
r`Set up and evaluate the volume of the cylinder \(x^2+y^2\le9\), \(0\le z\le4\).`,
r`Use cylindrical coordinates: \[V=\int_0^{2\pi}\int_0^3\int_0^4r\,dz\,dr\,d\theta=36\pi.\] This agrees with base area times height.`);
lesson('06-jacobians-surfaces','06 · Jacobians and surface area','Use a transformation to simplify a region and a cross product to measure surface area.',[A(3),T(3),F],[
 ['Change variables in the whole integral',r`For a smooth one-to-one transformation from \((u,v)\) to \((x,y)\), with nonzero Jacobian in the interior, \[\iint_R f(x,y)\,dA=\iint_S f(x(u,v),y(u,v))\left|\frac{\partial(x,y)}{\partial(u,v)}\right|du\,dv.\] Transform the region, the integrand, and the area element together.`],
 ['Use the correct determinant',r`The Jacobian needed for \(dx\,dy\) is \[\frac{\partial(x,y)}{\partial(u,v)}=\begin{vmatrix}x_u&x_v\\y_u&y_v\end{vmatrix}.\] If you instead computed \(\frac{\partial(u,v)}{\partial(x,y)}\), invert it where it is nonzero. The absolute value ensures that area does not become negative when a transformation reverses orientation.`],
 ['Parametric surface area',r`For a regular surface \(\mathbf r(u,v)\), the tangent vectors are \(\mathbf r_u\) and \(\mathbf r_v\). Their cross product supplies an oriented normal, and its length gives the local area scale: \[A=\iint_S\|\mathbf r_u\times\mathbf r_v\|\,du\,dv.\] Choose a parameter region covering the surface once, apart from boundary overlaps of zero area.`],
 ['Area of a graph',r`For \(z=g(x,y)\), use \(\mathbf r=\langle x,y,g(x,y)\rangle\). Then \[dS=\sqrt{1+g_x^2+g_y^2}\,dA.\] This is surface area, not the volume below the graph. Volume would integrate height; area integrates the local slope factor.`]
],r`Let \(u=x+y\) and \(v=x-y\), with \(0\le u\le2\) and \(0\le v\le1\). Solving gives \(x=\frac{u+v}{2}\), \(y=\frac{u-v}{2}\), and \[\left|\frac{\partial(x,y)}{\partial(u,v)}\right|=\frac12.\] Therefore \[\iint_R(x+y)\,dA=\int_0^1\int_0^2\frac{u}{2}\,du\,dv=1.\]`,
r`Find the area of \(z=2x+y\) above the unit square \(0\le x,y\le1\).`,
r`Since \(g_x=2\) and \(g_y=1\), \[A=\int_0^1\int_0^1\sqrt{1+4+1}\,dy\,dx=\sqrt6.\]`);
lesson('07-line-integrals','07 · Vector fields and line integrals','Compute divergence and curl, parameterize a path, and recognize conservative fields.',[A(3),A(4),T(3),F],[
 ['Divergence is scalar; curl is a vector',r`For \(\mathbf F=\langle P,Q,R\rangle\), \[\nabla\cdot\mathbf F=\frac{\partial P}{\partial x}+\frac{\partial Q}{\partial y}+\frac{\partial R}{\partial z}.\] Curl measures local rotation: \[\nabla\times\mathbf F=\left\langle R_y-Q_z,\ P_z-R_x,\ Q_x-P_y\right\rangle.\] Do not add all nine partial derivatives for divergence.`],
 ['Scalar integrals use speed',r`For a smooth path \(\mathbf r(t)\), \(a\le t\le b\), \[\int_C f\,ds=\int_a^b f(\mathbf r(t))\|\mathbf r'(t)\|\,dt.\] Reversing the direction of travel does not change this scalar integral. For a line segment from \(A\) to \(B\), use \(\mathbf r(t)=A+t(B-A)\), with \(0\le t\le1\).`],
 ['Work integrals use a dot product',r`A vector line integral is \[\int_C\mathbf F\cdot d\mathbf r=\int_a^b\mathbf F(\mathbf r(t))\cdot\mathbf r'(t)\,dt.\] Here the direction of the path matters: reversing it changes the sign. In two dimensions the same integral is written \(\int_C P\,dx+Q\,dy\).`],
 ['A potential replaces the path calculation',r`If \(\mathbf F=\nabla\Phi\), then \[\int_C\mathbf F\cdot d\mathbf r=\Phi(B)-\Phi(A).\] Find \(\Phi\) by integration, retaining an unknown function of the other variables, then match the remaining components. A continuously differentiable curl-free field on a simply connected open domain is conservative. A hole or singularity in the domain can invalidate the shortcut from zero curl alone.`]
],r`For \(\mathbf F=\langle2xy,x^2+2y\rangle\), integrate the first component with respect to \(x\): \(\Phi=x^2y+g(y)\). Matching \(\Phi_y=x^2+g'(y)=x^2+2y\) gives \(\Phi=x^2y+y^2\). The work from \((0,0)\) to \((1,2)\) is \[\Phi(1,2)-\Phi(0,0)=2+4=6.\]`,
r`Evaluate \(\int_C(x+y)\,ds\) along the straight segment from \((0,0)\) to \((1,1)\).`,
r`Use \(\mathbf r(t)=\langle t,t\rangle\), \(0\le t\le1\). The speed is \(\sqrt2\), so \[\int_C(x+y)\,ds=\int_0^1 2t\sqrt2\,dt=\sqrt2.\]`);
lesson('08-integral-theorems','08 · Green’s, divergence, and Stokes’ theorems','Choose the right theorem and keep the boundary orientation consistent.',[A(4),F],[
 ['Green’s theorem converts planar circulation',r`For a positively oriented, simple closed, piecewise smooth curve bounding a plane region, and a field with continuous first partials on an open set containing the region, \[\oint_C(P\,dx+Q\,dy)=\iint_R\left(\frac{\partial Q}{\partial x}-\frac{\partial P}{\partial y}\right)dA.\] Positive orientation is counterclockwise. Clockwise circulation changes the sign. Regions with holes require all boundary components with consistent orientation.`],
 ['Planar outward flux uses divergence',r`For the same regularity conditions, the two-dimensional flux form is \[\oint_C\mathbf F\cdot\mathbf n\,ds=\iint_R\left(\frac{\partial P}{\partial x}+\frac{\partial Q}{\partial y}\right)dA.\] Here \(\mathbf n\) is the outward unit normal. Circulation and outward flux are different quantities, even for the same field and curve.`],
 ['Closed surfaces use the divergence theorem',r`For a closed, piecewise smooth surface bounding a solid, with outward normal and a continuously differentiable field throughout the solid, \[\iint_{\partial Q}\mathbf F\cdot\mathbf n\,dS=\iiint_Q\nabla\cdot\mathbf F\,dV.\] An open surface needs its missing cap accounted for. Do not apply the theorem across a point where the field is undefined.`],
 ['Stokes’ theorem connects a surface to its boundary',r`For an oriented, piecewise smooth surface and a sufficiently smooth field, \[\oint_{\partial S}\mathbf F\cdot d\mathbf r=\iint_S(\nabla\times\mathbf F)\cdot\mathbf n\,dS.\] The boundary direction follows the right-hand rule relative to the normal. With an upward normal, a horizontal boundary is counterclockwise when viewed from above. The divergence and Stokes formulas appear on the supplied formula sheet; these sections provide additional practice beyond Assignment 4.`]
],r`Let \(\mathbf F=\langle-y,x\rangle\) around the circle of radius 2, counterclockwise. Green’s theorem gives \[\oint_C\mathbf F\cdot d\mathbf r=\iint_R(1-(-1))\,dA=2(4\pi)=8\pi.\] In contrast, \(\nabla\cdot\mathbf F=0\), so the outward flux across that circle is zero.`,
r`Use the divergence theorem to find outward flux of \(\mathbf F=\langle x,y,z\rangle\) through the unit sphere.`,
r`The divergence is 3 and the unit ball has volume \(\frac{4\pi}{3}\). Thus \[\iint_S\mathbf F\cdot\mathbf n\,dS=3\left(\frac{4\pi}{3}\right)=4\pi.\]`);

function q(topic,prompt,options,correct,explanation){questions.push({id:'m'+(questions.length+1),topic,prompt,options,correct,explanation});}
// Six original questions for each lesson; all numerical answers are exact unless stated.
q(0,r`For \(f=x^2y+\ln y\), \(y>0\), what is \(f_y\)?`,[r`\(2xy+\frac1y\)`,r`\(x^2+\frac1y\)`,r`\(x^2+y\)`,r`\(2x+\frac1y\)`],1,r`Hold \(x\) constant. Then \(\frac{\partial}{\partial y}(x^2y)=x^2\) and \(\frac{d}{dy}\ln y=\frac1y\).`);
q(0,r`If \(f=\frac{x}{x+y}\), what is \(f_x\)?`,[r`\(\frac1{x+y}\)`,r`\(\frac{-x}{(x+y)^2}\)`,r`\(\frac{y}{(x+y)^2}\)`,r`\(\frac{x+y}{y^2}\)`],2,r`The quotient rule gives \(f_x=\frac{(x+y)-x}{(x+y)^2}=\frac{y}{(x+y)^2}\), where \(x+y\ne0\).`);
q(0,r`For \(f=x^2y^3\), find \(f_{xy}(1,2)\).`,[r`\(12\)`,r`\(24\)`,r`\(8\)`,r`\(48\)`],1,r`First \(f_x=2xy^3\), then \(f_{xy}=6xy^2\). At \((1,2)\), this is \(6(1)(4)=24\).`);
q(0,r`Let \(z=u^2+v\), \(u=t^2\), \(v=3t\). Find \(\frac{dz}{dt}\) at \(t=1\).`,[r`\(3\)`,r`\(5\)`,r`\(7\)`,r`\(9\)`],2,r`The chain rule gives \(\frac{dz}{dt}=2u(2t)+3=4t^3+3\), hence 7 at \(t=1\).`);
q(0,r`Which surface is \(z=4-x^2-y^2\)?`,['A sphere','A downward-opening paraboloid','A circular cylinder','A plane'],1,r`Both horizontal variables enter quadratically with negative signs. The height is greatest at \((0,0)\) and decreases in every radial direction.`);
q(0,r`For \(f=e^{xy}\), what is \(f_x\)?`,[r`\(e^{xy}\)`,r`\(xe^{xy}\)`,r`\(xye^{xy}\)`,r`\(ye^{xy}\)`],3,r`Differentiate the exponent with respect to \(x\), holding \(y\) fixed: \(f_x=e^{xy}\frac{\partial(xy)}{\partial x}=ye^{xy}\).`);
q(1,r`For \(f=x^2+y^2\), the tangent plane at \((1,2,5)\) is:`,[r`\(z=2x+4y-5\)`,r`\(z=x+2y\)`,r`\(z=2x+4y+5\)`,r`\(z=2x+2y-1\)`],0,r`Use \(f_x=2\), \(f_y=4\) at the point: \(z=5+2(x-1)+4(y-2)=2x+4y-5\).`);
q(1,r`For \(f=x^2+y^2\) at \((1,2)\), find the directional derivative toward \(\langle3,4\rangle\).`,[r`\(22\)`,r`\(\frac{11}{5}\)`,r`\(\frac{22}{5}\)`,r`\(5\)`],2,r`Normalize to \(\mathbf u=\langle\frac35,\frac45\rangle\). Dot with \(\nabla f=\langle2,4\rangle\) to obtain \(\frac65+\frac{16}{5}=\frac{22}{5}\).`);
q(1,r`If \(\nabla f=\langle3,-4\rangle\), the maximum directional derivative is:`,[r`\(-1\)`,r`\(7\)`,r`\(25\)`,r`\(5\)`],3,r`The maximum is the gradient magnitude \(\sqrt{3^2+(-4)^2}=5\).`);
q(1,r`For \(f=\frac{x^2}{y}\), estimate the worst-case relative error when input errors are 1% in \(x\) and 2% in \(y\).`,['0%','2%','4%','6%'],2,r`The differential gives \(\frac{df}{f}=2\frac{dx}{x}-\frac{dy}{y}\). Add absolute contributions: \(2(1\%)+2\%=4\%\).`);
q(1,r`For \(f=xy\), use linearization at \((2,3)\) to estimate \(f(2.1,2.9)\).`,[r`\(6.10\)`,r`\(6.09\)`,r`\(5.90\)`,r`\(6.20\)`],0,r`At the base point \(f=6\), \(f_x=3\), \(f_y=2\). The linear estimate is \(6+3(0.1)+2(-0.1)=6.10\). The exact value 6.09 includes a second-order product.`);
q(1,r`At \((1,0,0)\), a tangent direction to the intersection of \(x^2+y^2+z^2=1\) and \(z=0\) is:`,[r`\(\langle1,0,0\rangle\)`,r`\(\langle0,1,0\rangle\)`,r`\(\langle0,0,1\rangle\)`,r`\(\langle1,1,1\rangle\)`],1,r`The normals are \(\langle2,0,0\rangle\) and \(\langle0,0,1\rangle\). Their cross product is \(\langle0,-2,0\rangle\); any nonzero scalar multiple, including \(\langle0,1,0\rangle\), is tangent.`);
q(2,r`Classify the origin for \(f=x^2-y^2\).`,['Local minimum','Local maximum','Saddle point','The origin is not critical'],2,r`Both first partials vanish there. The Hessian determinant is \(2(-2)-0=-4<0\), so it is a saddle.`);
q(2,r`If \(D=0\) in the two-variable second derivative test, what follows?`,['A local minimum','A local maximum','A saddle point','The test is inconclusive'],3,r`A zero determinant does not classify the point. Inspect the function by another method.`);
q(2,r`Minimize \(x^2+y^2\) subject to \(x+y=6\). The minimum value is:`,[r`\(6\)`,r`\(9\)`,r`\(18\)`,r`\(36\)`],2,r`Lagrange equations yield \(2x=\lambda=2y\). Hence \(x=y=3\), giving \(f=18\). Equivalently \(x^2+(6-x)^2=2(x-3)^2+18\).`);
q(2,r`What is the maximum of \(xy\) on the circle \(x^2+y^2=2\)?`,[r`\(1\)`,r`\(2\)`,r`\(\sqrt2\)`,r`\(0\)`],0,r`Since \((x-y)^2\ge0\), \(2xy\le x^2+y^2=2\). Equality holds at \((1,1)\) and \((-1,-1)\), so the maximum is 1.`);
q(2,r`The absolute minimum of \(f=x+y\) on \(0\le x,y\le1\) is:`,[r`\(1\) at \((0,1)\)`,r`\(0\) at \((0,0)\)`,'No minimum because the gradient never vanishes',r`\(2\) at \((1,1)\)`],1,r`Both coordinates are nonnegative, so \(x+y\ge0\), attained at the boundary corner \((0,0)\). Interior critical points alone would miss it.`);
q(2,r`For \(f=x^2+3y^2-4x+6y\), the critical point is:`,[r`\((2,-1)\)`,r`\((-2,1)\)`,r`\((4,-6)\)`,r`\((1,-2)\)`],0,r`Solve \(f_x=2x-4=0\) and \(f_y=6y+6=0\), giving \((2,-1)\).`);
q(3,r`Evaluate \(\int_0^1\int_0^x1\,dy\,dx\).`,[r`\(1\)`,r`\(\frac12\)`,r`\(\frac13\)`,r`\(2\)`],1,r`The inner integral is \(x\). Then \(\int_0^1x\,dx=\frac12\), the triangle's area.`);
q(3,r`Reverse the order for the region \(0\le x\le1\), \(0\le y\le x^2\).`,[r`\(0\le y\le1,\quad0\le x\le\sqrt y\)`,r`\(0\le y\le1,\quad y^2\le x\le1\)`,r`\(0\le y\le1,\quad\sqrt y\le x\le1\)`,r`\(0\le y\le x^2,\quad0\le x\le1\)`],2,r`A horizontal slice at height \(y\) runs from the curve \(x=\sqrt y\) to \(x=1\). The total range of \(y\) is 0 to 1.`);
q(3,r`Which area element belongs to polar coordinates?`,[r`\(dr\,d\theta\)`,r`\(r\,dr\,d\theta\)`,r`\(r^2\,dr\,d\theta\)`,r`\(\sin\theta\,dr\,d\theta\)`],1,r`The polar transformation scales area by its Jacobian \(r\).`);
q(3,r`Evaluate \(\iint_R(x^2+y^2)\,dA\) over the unit disk.`,[r`\(\pi\)`,r`\(2\pi\)`,r`\(\frac{\pi}{4}\)`,r`\(\frac{\pi}{2}\)`],3,r`Use \(\int_0^{2\pi}\int_0^1 r^3\,dr\,d\theta=2\pi\left(\frac14\right)=\frac\pi2\).`);
q(3,r`A uniform lamina occupies \(0\le x\le2\), \(0\le y\le4\). Its centroid is:`,[r`\((1,2)\)`,r`\((2,4)\)`,r`\((\frac12,\frac14)\)`,r`\((2,1)\)`],0,r`Uniform density and reflection symmetry place the centroid at each interval's midpoint: \(\bar x=1\), \(\bar y=2\).`);
q(3,r`For a planar lamina, which integrand defines moment of inertia about the x-axis?`,[r`\(x\delta\)`,r`\(x^2\delta\)`,r`\(y^2\delta\)`,r`\((x+y)\delta\)`],2,r`The perpendicular distance from \((x,y)\) to the x-axis is \(|y|\), so \(I_x=\iint_R y^2\delta\,dA\).`);
q(4,r`In cylindrical coordinates, \(\sqrt{x^2+y^2}\,dV\) becomes:`,[r`\(r\,dz\,dr\,d\theta\)`,r`\(r^2\,dz\,dr\,d\theta\)`,r`\(r^3\,dz\,dr\,d\theta\)`,r`\(\rho^2\sin\phi\,d\rho\,d\phi\,d\theta\)`],1,r`The integrand becomes \(r\) and \(dV\) contributes another \(r\). Their product is \(r^2\).`);
q(4,r`Which is the spherical volume element when \(\phi\) is measured from the positive z-axis?`,[r`\(\rho\,d\rho\,d\phi\,d\theta\)`,r`\(\rho^2\cos\phi\,d\rho\,d\phi\,d\theta\)`,r`\(\rho^2\sin\phi\,d\rho\,d\phi\,d\theta\)`,r`\(\sin\theta\,d\rho\,d\phi\,d\theta\)`],2,r`The spherical Jacobian for this convention is \(\rho^2\sin\phi\).`);
q(4,r`For the upper hemisphere, what is the range of \(\phi\)?`,[r`\(0\le\phi\le2\pi\)`,r`\(0\le\phi\le\pi\)`,r`\(-\pi\le\phi\le0\)`,r`\(0\le\phi\le\frac\pi2\)`],3,r`The upper half has \(z=\rho\cos\phi\ge0\), so the polar angle ranges from 0 to \(\frac\pi2\).`);
q(4,r`The cone \(z=\sqrt{x^2+y^2}\) corresponds to which spherical angle?`,[r`\(\phi=\frac\pi4\)`,r`\(\phi=\frac\pi2\)`,r`\(\theta=\frac\pi4\)`,r`\(\rho=1\)`],0,r`The equation becomes \(\rho\cos\phi=\rho\sin\phi\), hence \(\tan\phi=1\) and \(\phi=\frac\pi4\), away from the origin.`);
q(4,r`Evaluate \(\iiint_Q1\,dV\) for the ball of radius 2.`,[r`\(8\pi\)`,r`\(\frac{16\pi}{3}\)`,r`\(\frac{32\pi}{3}\)`,r`\(32\pi\)`],2,r`The volume is \(\frac43\pi(2^3)=\frac{32\pi}{3}\). Spherical integration gives the same result.`);
q(4,r`For the solid \(0\le x\le1\), \(0\le y\le1-x\), \(0\le z\le2\), the volume is:`,[r`\(\frac12\)`,r`\(1\)`,r`\(2\)`,r`\(4\)`],1,r`The triangular base has area \(\frac12\) and height 2. Equivalently \(\int_0^1\int_0^{1-x}\int_0^2 1\,dz\,dy\,dx=1\).`);
q(5,r`For \(u=x+y\), \(v=x-y\), what is \(\left|\frac{\partial(x,y)}{\partial(u,v)}\right|\)?`,[r`\(2\)`,r`\(-2\)`,r`\(\frac12\)`,r`\(1\)`],2,r`The forward determinant is \(-2\), so the inverse determinant is \(-\frac12\). Its absolute value is \(\frac12\).`);
q(5,r`If \(x=2u\) and \(y=3v\), then \(dA\) equals:`,[r`\(6\,du\,dv\)`,r`\(\frac16\,du\,dv\)`,r`\(5\,du\,dv\)`,r`\(du\,dv\)`],0,r`The determinant is \(\begin{vmatrix}2&0\\0&3\end{vmatrix}=6\), so area scales by 6.`);
q(5,r`Find the area of \(z=2x+y\) above the unit square.`,[r`\(6\)`,r`\(\sqrt5\)`,r`\(\frac32\)`,r`\(\sqrt6\)`],3,r`The area factor is \(\sqrt{1+2^2+1^2}=\sqrt6\). Multiplying by the unit base area gives \(\sqrt6\).`);
q(5,r`Which expression measures parametric surface area?`,[r`\(\iint\mathbf r_u\cdot\mathbf r_v\,du\,dv\)`,r`\(\iint\|\mathbf r_u\times\mathbf r_v\|\,du\,dv\)`,r`\(\iint\|\mathbf r\|\,du\,dv\)`,r`\(\iint1\,du\,dv\)`],1,r`The cross-product magnitude gives the area of the parallelogram spanned by the two tangent vectors.`);
q(5,r`A sphere has radius 3. Its surface area is:`,[r`\(9\pi\)`,r`\(12\pi\)`,r`\(36\pi\)`,r`\(\frac{4\pi}{3}\)`],2,r`Parameterizing a sphere gives area factor \(9\sin\phi\). Integrate over \(0\le\phi\le\pi\), \(0\le\theta\le2\pi\) to obtain \(36\pi\).`);
q(5,r`For \(u=x+y\), \(v=x-y\), the region \(0\le u\le2\), \(0\le v\le1\) has area in the xy-plane:`,[r`\(1\)`,r`\(2\)`,r`\(4\)`,r`\(\frac12\)`],0,r`The rectangle in the uv-plane has area 2. Multiply by the inverse Jacobian magnitude \(\frac12\), giving area 1.`);
q(6,r`For \(\mathbf F=\langle x^2,y^2,z^2\rangle\), the divergence is:`,[r`\(x+y+z\)`,r`\(2x+2y+2z\)`,r`\(\langle2x,2y,2z\rangle\)`,r`\(0\)`],1,r`Add the matching partial derivatives: \(\frac{\partial x^2}{\partial x}+\frac{\partial y^2}{\partial y}+\frac{\partial z^2}{\partial z}=2x+2y+2z\). The result is scalar.`);
q(6,r`For \(\mathbf F=\langle-y,x,0\rangle\), the curl is:`,[r`\(\langle0,0,0\rangle\)`,r`\(\langle0,0,1\rangle\)`,r`\(\langle0,0,2\rangle\)`,r`\(2\)`],2,r`Only the third component is nonzero: \(Q_x-P_y=1-(-1)=2\).`);
q(6,r`The speed of \(\mathbf r(t)=\langle3\cos t,3\sin t,4t\rangle\) is:`,[r`\(3\)`,r`\(4\)`,r`\(7\)`,r`\(5\)`],3,r`The derivative is \(\langle-3\sin t,3\cos t,4\rangle\), whose magnitude is \(\sqrt{9\sin^2t+9\cos^2t+16}=5\).`);
q(6,r`For \(\Phi=x^2+y^2\), find the work of \(\nabla\Phi\) from \((1,0)\) to \((0,2)\).`,[r`\(3\)`,r`\(5\)`,r`\(-3\)`,r`\(0\)`],0,r`Use final potential minus initial potential: \(4-1=3\).`);
q(6,r`Reversing an oriented path changes \(\int_C\mathbf F\cdot d\mathbf r\) by:`,['Leaving it unchanged','Changing its sign','Squaring its value','Multiplying by path length'],1,r`Reversal changes the sign of the tangent direction. Scalar integrals with \(ds\) do not have this sign change.`);
q(6,r`Find \(\int_C(x+y)\,ds\) on the segment from \((0,0)\) to \((1,1)\).`,[r`\(1\)`,r`\(2\)`,r`\(\sqrt2\)`,r`\(2\sqrt2\)`],2,r`With \(\mathbf r(t)=\langle t,t\rangle\), integrate \(\int_0^1(2t)\sqrt2\,dt=\sqrt2\).`);
q(7,r`In Green’s circulation theorem, the double-integral integrand is:`,[r`\(P_x+Q_y\)`,r`\(P_y-Q_x\)`,r`\(P_x-Q_y\)`,r`\(Q_x-P_y\)`],3,r`For a positively oriented boundary, \(\oint_C P\,dx+Q\,dy=\iint_R(Q_x-P_y)\,dA\).`);
q(7,r`Find the counterclockwise circulation of \(\mathbf F=\langle-y,x\rangle\) around the unit circle.`,[r`\(0\)`,r`\(2\pi\)`,r`\(\pi\)`,r`\(-2\pi\)`],1,r`Green’s theorem gives constant integrand \(1-(-1)=2\). Multiply by the unit disk's area \(\pi\).`);
q(7,r`Find outward flux of \(\mathbf F=\langle x,y\rangle\) across the circle of radius 2.`,[r`\(8\pi\)`,r`\(4\pi\)`,r`\(2\pi\)`,r`\(0\)`],0,r`The planar divergence is 2, so outward flux is \(2\times\pi(2^2)=8\pi\).`);
q(7,r`Find outward flux of \(\mathbf F=\langle x,y,z\rangle\) through the unit sphere.`,[r`\(\frac{4\pi}{3}\)`,r`\(12\pi\)`,r`\(4\pi\)`,r`\(0\)`],2,r`Divergence is 3. The divergence theorem gives \(3\times\frac{4\pi}{3}=4\pi\).`);
q(7,r`For an upward-oriented horizontal disk, the positive boundary direction in Stokes’ theorem is:`,['Clockwise viewed from above','Either direction with no sign change','Radially outward','Counterclockwise viewed from above'],3,r`The right-hand rule pairs an upward thumb with a counterclockwise boundary viewed from above.`);
q(7,r`What must you check before using a divergence theorem on a region?`,['The field has zero curl','The field is continuously differentiable throughout the region and the required boundary is closed','The region is a sphere','The divergence is constant'],1,r`The theorem needs a suitable closed boundary and field regularity across the enclosed region. Singularities cannot simply be ignored; the divergence need not be constant.`);
module.exports={id:'math250b',testMinutes:60,lessons,questions,sources:[A(1),A(2),A(3),A(4),F,T(1),T(2),T(3)],referenceDirectory:'Math 250B'};
