// Original beginner lessons aligned to the instructor's section sequence.
const r=String.raw, lessons=[];
function L(slug,title,unit,sections,summary,prereq,idea,method,examples,practice,pitfall){lessons.push({slug,title,unit,sections,summary,prereq,idea,method,examples,practice,pitfall});}
const E=(title,problem,steps,answer,check)=>({title,problem,steps,answer,check});
L('01-reading-equations','Reading a differential equation',1,['1.1','1.2'],'Understand what you are solving for, what a derivative means, and what an initial condition adds.','Basic derivatives and substitution.',[
['The unknown is a function',r`An algebra equation asks for a number. A differential equation asks for a function whose derivatives satisfy a relationship. In \(y'=2x\), the unknown is \(y(x)\). The prime is shorthand for \(dy/dx\), the rate at which \(y\) changes with \(x\).`],
['Order and linearity',r`The order is the highest derivative present: \(y''+y=0\) is second order. A linear equation contains the unknown function and its derivatives only to the first power, with coefficients depending only on the independent variable. Thus \(xy'+y=x^2\) is linear, but \(y'=y^2\) and \(yy''=1\) are nonlinear.`],
['A family versus one member',r`Integrating \(y'=2x\) gives the family \(y=x^2+C\). An initial condition, such as \(y(0)=3\), selects a member. A solution must be differentiable enough and satisfy the equation on an interval, not just at one point.`],
['When an IVP has one local solution',r`For \(y'=f(x,y)\), continuity of \(f\) and \(\partial f/\partial y\) in a rectangle around the initial point is a sufficient condition for one local solution. If these conditions fail, the test is inconclusive; it does not automatically mean no solution exists.`]
],['Identify the independent variable, unknown function, and highest derivative.','Differentiate a proposed solution before substituting it into the equation.','Use every initial condition and state any interval restrictions.'],[
E('Verify and select a solution',r`Show that \(y=Ce^{-2x}\) solves \(y'+2y=0\), then impose \(y(0)=3\).`,[
['Differentiate the candidate',r`The chain rule gives \[y'=-2Ce^{-2x}.\] The constant \(C\) stays as a multiplier.`],['Substitute both terms',r`The left side becomes \[-2Ce^{-2x}+2Ce^{-2x}=0.\] So every member satisfies the differential equation.`],['Use the initial condition',r`At \(x=0\), \(e^0=1\). Therefore \(C=3\).`]],r`y=3e^{-2x},\qquad -\infty<x<\infty`,r`The value at zero is 3 and the derivative is always negative when the solution is positive.`)
],E('Your turn',r`Solve \(y'=6x\) with \(y(1)=5\).`,[['Integrate',r`\[y=3x^2+C.\] One integration introduces one arbitrary constant.`],['Apply the given value',r`\[5=3(1)^2+C\quad\Rightarrow\quad C=2.\]`]],r`y=3x^2+2`,r`Differentiating gives \(6x\), and substituting \(x=1\) gives 5.`),'A solution must satisfy both the equation and the initial condition. Checking only one is not enough.');
L('02-separable','Separable equations',1,['2.2'],'Separate the two variables, integrate, and recover the constant solutions that division can hide.','Antiderivatives, logarithms, and exponentials.',[
['Spot the pattern',r`Use separation when \[\frac{dy}{dx}=g(x)h(y).\] On a region where \(h(y)\ne0\), rewrite this as \(dy/h(y)=g(x)\,dx\). You are using the chain rule in reverse.`],
['Check equilibria first',r`Any root \(h(c)=0\) gives a constant solution \(y=c\). Dividing by \(h(y)\) would remove it, so record these solutions before separating.`],
['Handle the constant carefully',r`Put one arbitrary constant on the final integrated equation. In \(\ln|y|=G(x)+C\), exponentiation gives \(y=Ae^{G(x)}\) on a nonzero branch. The sign is absorbed into \(A\); add the zero solution separately if valid.`]
],['Check for constant solutions.','Collect the y terms with dy and the x terms with dx.','Integrate both sides, then use the initial value.','Solve for y if practical and check the interval.'],[
E('Growth with a changing rate',r`Solve \(y'=2xy\), \(y(0)=3\).`,[['Separate',r`The zero solution exists but does not match the initial value. For the required nonzero branch, \[\frac{1}{y}\,dy=2x\,dx.\]`],['Integrate',r`\[\ln|y|=x^2+C\quad\Rightarrow\quad y=Ae^{x^2}.\]`],['Determine the constant',r`\(y(0)=A=3\). The result is defined for all real \(x\).`]],r`y=3e^{x^2}`,r`\(y'=6xe^{x^2}=2x(3e^{x^2})\), as required.`)
],E('Your turn',r`Solve \(y'=-y^2\), \(y(0)=2\).`,[['Separate and integrate',r`\[y^{-2}\,dy=-dx,\qquad -\frac1y=-x+C.\]`],['Use the initial value',r`\(-1/2=C\), so \(1/y=x+1/2\).`],['Choose the interval',r`The denominator vanishes at \(x=-1/2\). The largest solution interval containing zero is \((-1/2,\infty)\).`]],r`y=\frac{2}{1+2x},\qquad x>-\frac12`,r`\(y'=-4/(1+2x)^2=-y^2\). The additional equilibrium \(y=0\) does not satisfy this IVP.`),'Do not cancel a factor involving y without checking whether it can be zero.');
L('03-linear-first-order','First-order linear equations',1,['2.3'],'Turn the left side into one product derivative using an integrating factor.','The product rule and integration.',[
['Normalize first',r`The standard form is \[y'+P(x)y=Q(x).\] Divide by the coefficient of \(y'\) before identifying \(P\). Work on an interval where that coefficient is nonzero.`],
['Why the integrating factor works',r`Choose \[\mu(x)=e^{\int P(x)\,dx}.\] Because \(\mu'=P\mu\), multiplying the equation by \(\mu\) makes \(\mu y'+\mu Py=(\mu y)'\). Hence \[y=\frac{1}{\mu}\left(\int\mu Q\,dx+C\right).\] You may choose one convenient antiderivative in the exponent; an extra constant factor is unnecessary.`]
],['Divide into standard form.','Find the integrating factor.','Multiply every term and identify the product derivative.','Integrate, divide by the integrating factor, and apply the initial condition.'],[
E('A constant coefficient',r`Solve \(y'+2y=6\), \(y(0)=1\).`,[['Find the factor',r`\(P=2\), so \(\mu=e^{2x}\).`],['Multiply and integrate',r`\[(e^{2x}y)'=6e^{2x},\qquad e^{2x}y=3e^{2x}+C.\]`],['Isolate y',r`\(y=3+Ce^{-2x}\). At zero, \(1=3+C\), so \(C=-2\).`]],r`y=3-2e^{-2x}`,r`\(y'+2y=4e^{-2x}+6-4e^{-2x}=6\). The solution approaches the equilibrium 3.`)
],E('Your turn',r`Solve \(xy'+y=x^2\), \(y(1)=2\), on \(x>0\).`,[['Normalize',r`\[y'+\frac1x y=x.\] Thus \(P=1/x\), not 1.`],['Multiply by the factor',r`On \(x>0\), \(\mu=e^{\ln x}=x\), so \[(xy)'=x^2.\]`],['Integrate and apply the condition',r`\[xy=\frac{x^3}{3}+C,\qquad 2=\frac13+C.\] Thus \(C=5/3\).`]],r`y=\frac{x^2}{3}+\frac{5}{3x},\qquad x>0`,r`\(xy'+y=x(2x/3-5/(3x^2))+x^2/3+5/(3x)=x^2\).`),'The integrating factor must multiply the right side too.');
L('04-exact','Exact equations',1,['2.4'],'Recognize a hidden total derivative and reconstruct its potential function.','Partial derivatives and integration with one variable held constant.',[
['The hidden function',r`Write the equation as \[M(x,y)\,dx+N(x,y)\,dy=0.\] It is exact when a function \(F\) satisfies \(F_x=M\) and \(F_y=N\). Then \(dF=0\), so solutions lie on \(F(x,y)=C\).`],
['Test before integrating',r`With continuous first partials on a simply connected region, the test is \[M_y=N_x.\] When you integrate \(M\) with respect to \(x\), the constant can depend on \(y\): write \(F=\int M\,dx+g(y)\).`],
['If the first test fails',r`Some equations become exact after multiplication by an integrating factor. If \((M_y-N_x)/N\) is a function of \(x\) alone, use its integral in \(\mu(x)=e^{\int (M_y-N_x)/N\,dx}\). If \((N_x-M_y)/M\) depends only on \(y\), use \(\mu(y)=e^{\int (N_x-M_y)/M\,dy}\). These tests apply where the denominators are nonzero; check the multiplied equation again.`]
],['Identify M and N and compare the cross partials.','Integrate M in x, adding g(y).','Differentiate that result in y and match N to find g.','Write F=C and use any initial condition.'],[
E('Recover the hidden potential',r`Solve \((2xy+3)\,dx+(x^2+4y)\,dy=0\) through \((0,1)\).`,[['Test exactness',r`\(M_y=2x=N_x\), so the equation is exact.`],['Integrate M',r`\[F=x^2y+3x+g(y).\] The term \(g\) is a function, not yet a numerical constant.`],['Match the other partial',r`\[F_y=x^2+g'(y)=x^2+4y.\] Hence \(g'=4y\) and we can take \(g=2y^2\).`],['Apply the initial point',r`At \((0,1)\), \(F=2\). An implicit answer is completely acceptable.`]],r`x^2y+3x+2y^2=2`,r`Differentiating this level curve gives precisely the original differential form.`)
],E('Your turn',r`Solve \((2x+y)\,dx+(x+2y)\,dy=0\) through \((1,0)\).`,[['Test and integrate',r`\(M_y=N_x=1\). Integrating \(M\) gives \(F=x^2+xy+g(y)\).`],['Match N',r`\(F_y=x+g'(y)=x+2y\), so \(g=y^2\).`],['Use the point',r`\(F(1,0)=1\).`]],r`x^2+xy+y^2=1`,r`The differential is \((2x+y)dx+(x+2y)dy\).`),'Integrating M in x does not make all y-dependent terms disappear: they belong in g(y).');
L('05-substitutions','Substitutions: homogeneous and Bernoulli',1,['2.5'],'Replace a difficult expression with a new variable so a familiar method becomes available.','Separation, integrating factors, and the chain rule.',[
['A ratio suggests y=vx',r`If \(y'=F(y/x)\), set \(v=y/x\), or \(y=xv\). The product rule gives \[y'=v+xv'.\] Substitute both expressions. The resulting equation in \(v\) and \(x\) is often separable. Work away from \(x=0\). Here “homogeneous” refers to dependence on the ratio, not to a zero forcing term.`],
['A power suggests Bernoulli',r`For \[y'+P(x)y=Q(x)y^n,\qquad n\ne0,1,\] set \(v=y^{1-n}\). On a suitable nonzero branch, dividing by \(y^n\) and applying the chain rule gives \[v'+(1-n)Pv=(1-n)Q.\] This is linear in \(v\). Check lost zero solutions in the original equation.`],
['A combined expression can be the variable',r`For \(y'=f(ax+by+c)\), try \(u=ax+by+c\). Then \(u'=a+b y'\), giving \(u'=a+b f(u)\), which is separable when applicable. Always translate the initial condition into the new variable.`]
],['Recognize the pattern and define the new variable.','Differentiate the substitution carefully.','Solve the transformed equation.','Substitute back and check the original equation.'],[
E('A ratio substitution',r`Solve \(y'=1+y/x\), \(y(1)=0\), on \(x>0\).`,[['Replace y and its derivative',r`\[y=xv,\qquad v+xv'=1+v.\] The \(v\) terms cancel.`],['Solve for v',r`\[v'=\frac1x\quad\Rightarrow\quad v=\ln x+C.\]`],['Return to y',r`\(y=x(\ln x+C)\). The initial condition gives \(C=0\).`]],r`y=x\ln x,\qquad x>0`,r`\(y'=\ln x+1=1+y/x\).`),
E('Bernoulli becomes linear',r`Solve \(y'+y=y^2\), \(y(0)=1/2\).`,[['Choose the substitution',r`Here \(n=2\), so \(v=y^{-1}\). Dividing by \(y^2\) gives \(-v'+v=1\), or \(v'-v=-1\).`],['Solve the linear equation',r`A constant particular solution is 1. The general solution is \(v=1+Ce^x\).`],['Translate the initial value',r`\(v(0)=1/y(0)=2\), so \(C=1\). Invert to return to \(y\).`]],r`y=\frac{1}{1+e^x}`,r`\(y'+y=-e^x/(1+e^x)^2+1/(1+e^x)=1/(1+e^x)^2=y^2\).`)
],E('Your turn',r`Solve \(y'=(x+y)^2\), \(y(0)=0\), near zero.`,[['Set u=x+y',r`\(u'=1+y'=1+u^2\) and \(u(0)=0\).`],['Separate and integrate',r`\[\frac{du}{1+u^2}=dx\quad\Rightarrow\quad \arctan u=x+C.\] At zero, \(C=0\).`],['Undo the substitution',r`\(u=\tan x\), hence \(y=u-x\). Choose the interval containing zero before the tangent has a pole.`]],r`y=\tan x-x,\qquad -\frac\pi2<x<\frac\pi2`,r`\(y'=\sec^2x-1=\tan^2x=(x+y)^2\).`),'For y=xv, the derivative is v+xv′, not just xv′.');
L('06-first-order-models','Growth, cooling, and mixing',1,['3.1'],'Translate a short word problem into a rate equation with consistent units.','Separation, first-order linear equations, and logarithms.',[
['Growth or decay',r`“Rate proportional to the amount” means \(A'=kA\), so \(A=A_0e^{kt}\). Positive \(k\) means growth and negative \(k\) means decay. Use a measurement to find \(k\); do not guess it from a percentage without accounting for elapsed time.`],
['Cooling toward the surroundings',r`For constant ambient temperature \(T_a\), Newton’s model is \[T'=-k(T-T_a),\qquad k>0.\] Thus \(T-T_a=(T_0-T_a)e^{-kt}\). The decaying quantity is the temperature difference, not the temperature itself.`],
['Mixing is a balance',r`Let \(m\) be the mass of dissolved salt. Then \[m'=\text{mass rate in}-\text{mass rate out}.\] With flow in litres per minute and concentration in grams per litre, each product is grams per minute. The outgoing concentration is \(m(t)/V(t)\). If the flows differ, use \(V(t)=V_0+(q_{in}-q_{out})t\) while the tank model remains valid.`]
],['Define the quantity, its units, and the time unit.','Translate each rate separately before simplifying.','Solve the IVP, then answer the question in words and units.','Check the initial value and long-term behaviour.'],[
E('A well-mixed tank',r`A tank holds 100 L of fresh water. Brine at 2 g/L enters at 5 L/min; mixed liquid leaves at 5 L/min. Find the salt mass after t minutes.`,[['Write the two rates',r`Input is \(2\cdot5=10\) g/min. Output is \((m/100)\cdot5=m/20\) g/min. Equal flows keep the volume at 100 L.`],['Build and solve the equation',r`\[m'+\frac1{20}m=10,\qquad m(0)=0.\] A constant particular solution is 200, giving \(m=200+Ce^{-t/20}\).`],['Apply the initial mass',r`\(0=200+C\), so \(C=-200\).`]],r`m(t)=200(1-e^{-t/20})\ \text{g},\qquad t\ge0`,r`At long times the concentration tends to \(200/100=2\) g/L, the incoming concentration.`),
E('A doubling time',r`A population starts at 200 and doubles in 3 hours. Find its exponential model.`,[['Start with the initial amount',r`\(A(t)=200e^{kt}\).`],['Use the second measurement',r`\[400=200e^{3k}\quad\Rightarrow\quad k=\frac{\ln2}{3}.\]`],['Express the model',r`Each three-hour period contributes one factor of 2.`]],r`A(t)=200e^{(\ln2)t/3}=200\cdot2^{t/3}`,r`At 6 hours, \(A=800\), which is two doublings.`)
],E('Your turn',r`An object cools from 80°C to 50°C in 10 minutes in a 20°C room. When does it reach 35°C?`,[['Model the difference',r`\[T=20+60e^{-kt}.\]`],['Find k',r`\(50=20+60e^{-10k}\) gives \(e^{-10k}=1/2\), so \(k=\ln2/10\).`],['Solve for the requested temperature',r`\(35=20+60e^{-kt}\) gives \(e^{-kt}=1/4\). Hence \(t=\ln4/k=20\).`]],r`t=20\ \text{minutes}`,r`The excess temperature halves every 10 minutes: 60, then 30, then 15 degrees.`),'In a tank problem, mass and concentration are different quantities. Use mass divided by volume for the outgoing concentration.');
L('07-linear-theory','Linear theory and reduction of order',2,['4.1','4.2'],'Understand why solutions combine, and find a second solution when one is already known.','Product rule, integration, and first-order equations.',[
['The complementary and particular parts',r`For \(y''+P(x)y'+Q(x)y=g(x)\), the homogeneous equation has zero on the right. If \(y_1,y_2\) are independent homogeneous solutions, \[y=C_1y_1+C_2y_2+y_p,\] where \(y_p\) is any one solution of the full equation. Independence means neither solution is a constant multiple of the other.`],
['Check independence with the Wronskian',r`\[W=y_1y_2'-y_1'y_2.\] For two solutions of the same homogeneous linear equation with continuous normalized coefficients, a nonzero Wronskian at one point proves independence throughout the interval. A second-order IVP supplies two conditions, usually \(y(x_0)\) and \(y'(x_0)\).`],
['Reduction of order',r`Given a nonzero known solution \(y_1\), try \(y=vy_1\). The product rule turns the original second-order equation into a first-order equation for \(v'\). Equivalently, after normalization, \[y_2=y_1\int\frac{e^{-\int P(x)\,dx}}{y_1^2}\,dx.\] Work where the coefficients and division by \(y_1\) are valid.`]
],['Normalize the equation and identify its homogeneous part.','For reduction of order, set y=vy₁ and compute both derivatives.','Substitute, cancel, and solve for v′.','Integrate once more and keep a genuinely independent solution.'],[
E('Find the missing solution',r`For \(y''-2y'+y=0\), one solution is \(y_1=e^x\). Find a second.`,[['Apply the product rule twice',r`\[y=ve^x,\quad y'=e^x(v'+v),\quad y''=e^x(v''+2v'+v).\]`],['Substitute and simplify',r`\[y''-2y'+y=e^xv''=0.\] Thus \(v''=0\).`],['Integrate and separate the two parts',r`\(v=Ax+B\), hence \(y=Axe^x+Be^x\). The new solution is \(xe^x\).`]],r`y=C_1e^x+C_2xe^x`,r`\(W(e^x,xe^x)=e^{2x}\ne0\), proving independence.`)
],E('Your turn',r`For \(y''=0\), start with \(y_1=1\). Find the solution with \(y(0)=2\), \(y'(0)=3\).`,[['Find the second solution',r`Writing \(y=v\cdot1\) gives \(v''=0\), so an independent choice is \(y_2=x\).`],['Apply the two conditions',r`\(y=C_1+C_2x\), so \(C_1=2\) and \(C_2=3\).`]],r`y=2+3x`,r`Its second derivative is zero and both initial conditions hold.`),'A particular solution is just one solution of the forced equation; it does not replace the complementary solution.');
L('08-characteristic-roots','Constant coefficients and characteristic roots',2,['4.3'],'Turn differentiation into a polynomial, then translate its roots into real solutions.','Quadratic equations, exponentials, sine, and cosine.',[
['Why a polynomial appears',r`For \(ay''+by'+cy=0\), try \(y=e^{rx}\). Substitution gives \[e^{rx}(ar^2+br+c)=0.\] Since the exponential is nonzero, solve the characteristic equation \(ar^2+br+c=0\).`],
['Three root patterns',r`Distinct real roots \(r_1,r_2\) give \(C_1e^{r_1x}+C_2e^{r_2x}\). A repeated root \(r\) gives \((C_1+C_2x)e^{rx}\). Complex roots \(\alpha\pm i\beta\) give \[e^{\alpha x}(C_1\cos\beta x+C_2\sin\beta x).\] For higher-order equations, use all roots, with powers of \(x\) up to one less than each multiplicity.`]
],['Write the characteristic polynomial with the correct signs.','Find all roots and identify their pattern.','Write the complete real solution.','Differentiate before applying derivative initial conditions.'],[
E('Two distinct roots',r`Solve \(y''-3y'+2y=0\), \(y(0)=1\), \(y'(0)=0\).`,[['Factor the polynomial',r`\[r^2-3r+2=(r-1)(r-2).\] The roots are 1 and 2.`],['Write the solution and derivative',r`\[y=C_1e^x+C_2e^{2x},\qquad y'=C_1e^x+2C_2e^{2x}.\]`],['Solve the constant equations',r`\(C_1+C_2=1\), \(C_1+2C_2=0\). Subtracting gives \(C_2=-1\), then \(C_1=2\).`]],r`y=2e^x-e^{2x}`,r`At zero, \(y=2-1=1\) and \(y'=2-2=0\). Each exponential satisfies the ODE.`),
E('A repeated root',r`Find the general solution of \(y''+4y'+4y=0\).`,[['Factor',r`\((r+2)^2=0\), so \(r=-2\) is repeated.`],['Supply a second independent term',r`Two copies of \(e^{-2x}\) would combine into one constant. Multiply the second copy by \(x\).`]],r`y=(C_1+C_2x)e^{-2x}`,r`The Wronskian of \(e^{-2x}\) and \(xe^{-2x}\) is \(e^{-4x}\), which never vanishes.`)
],E('Your turn',r`Solve \(y''+4y=0\), \(y(0)=0\), \(y'(0)=6\).`,[['Identify complex roots',r`\(r^2+4=0\) gives \(r=\pm2i\). Thus \(y=C_1\cos2x+C_2\sin2x\).`],['Use the conditions',r`\(C_1=0\). The derivative at zero is \(2C_2=6\), so \(C_2=3\).`]],r`y=3\sin2x`,r`\(y''=-12\sin2x\), which cancels \(4y\).`),'With a repeated root, forgetting the factor x loses one independent solution.');
L('09-undetermined-coefficients','Undetermined coefficients and resonance',2,['4.4'],'Choose a trial particular solution and determine its coefficients by substitution.','Characteristic roots and matching coefficients.',[
['Choose this method for familiar forcing',r`For a constant-coefficient linear equation, this method works for sums of polynomial, exponential, sine, and cosine terms and their products. A polynomial of degree \(n\) needs a trial polynomial with every power down to the constant term.`],
['Match the family, not just the visible term',r`For \(e^{ax}\), try \(Ae^{ax}\). For \(\sin bx\) or \(\cos bx\), include both: \(A\cos bx+B\sin bx\). For a polynomial times \(e^{ax}\), multiply a full trial polynomial of the same degree by \(e^{ax}\).`],
['Fix overlap with the complementary solution',r`If the trial overlaps \(y_c\), multiply the whole trial by enough powers of \(x\) to remove the overlap. A simple characteristic root needs one factor \(x\); a double root needs \(x^2\). This is the resonance adjustment.`]
],['Find the complementary solution first.','Choose a trial matching the forcing and correct any overlap.','Differentiate and substitute, then solve for the trial coefficients.','Add the complementary solution before applying initial conditions.'],[
E('A forcing term with no overlap',r`Solve \(y''-y=e^{2x}\) in general form.`,[['Find the complementary solution',r`Roots \(\pm1\) give \(y_c=C_1e^x+C_2e^{-x}\).`],['Choose and substitute the trial',r`Since 2 is not a root, try \(y_p=Ae^{2x}\). Then \[y_p''-y_p=(4A-A)e^{2x}=3Ae^{2x}.\]`],['Match the coefficient',r`\(3A=1\), so \(A=1/3\).`]],r`y=C_1e^x+C_2e^{-x}+\frac13e^{2x}`,r`The complementary terms contribute zero and the last term contributes exactly \(e^{2x}\).`),
E('A resonant forcing term',r`Find a particular solution of \(y''-y=e^x\).`,[['Notice the overlap',r`\(e^x\) is already in \(y_c\). The trial \(Ae^x\) would contribute zero, so use \(Axe^x\).`],['Differentiate',r`\[y_p'=Ae^x(x+1),\qquad y_p''=Ae^x(x+2).\]`],['Substitute',r`\(y_p''-y_p=2Ae^x\), so \(A=1/2\).`]],r`y_p=\frac12xe^x`,r`The factor \(x\) makes the trial independent of the complementary solution.`)
],E('Your turn',r`Find the general solution of \(y''+y=2\).`,[['Solve the homogeneous equation',r`Roots \(\pm i\) give \(y_c=C_1\cos x+C_2\sin x\).`],['Try a constant',r`Set \(y_p=A\). Its second derivative vanishes, so \(A=2\).`]],r`y=C_1\cos x+C_2\sin x+2`,r`The sine and cosine terms cancel with their second derivatives, leaving 2.`),'Initial conditions apply to y=y_c+y_p, not to y_c alone.');
L('10-variation-of-parameters','Variation of parameters',2,['4.6'],'Use a general method when a simple trial function will not work.','Integration, Wronskians, and homogeneous solutions.',[
['Let the constants become functions',r`Normalize to \(y''+Py'+Qy=g\), and find independent homogeneous solutions \(y_1,y_2\). Seek \(y_p=u_1y_1+u_2y_2\). Impose \(u_1'y_1+u_2'y_2=0\) to simplify the derivatives.`],
['Solve for the new derivatives',r`Using \(W=y_1y_2'-y_1'y_2\), \[u_1'=-\frac{y_2g}{W},\qquad u_2'=\frac{y_1g}{W}.\] Integrate these and substitute into \(y_p\). Constants of integration in the \(u\)'s can be set to zero because their contributions are already in \(y_c\).`]
],['Divide by the leading coefficient before identifying g.','Find y₁, y₂, and the Wronskian.','Integrate the two parameter derivatives.','Form y_p and add y_c; keep the domain of all functions.'],[
E('A forcing term outside the trial table',r`Solve \(y''+y=\sec x\) on \(-\pi/2<x<\pi/2\).`,[['Find the homogeneous pair',r`Take \(y_1=\cos x\), \(y_2=\sin x\), giving \(W=\cos^2x+\sin^2x=1\).`],['Find and integrate the parameters',r`\[u_1'=-\sin x\sec x=-\tan x,\qquad u_2'=\cos x\sec x=1.\] On this interval, \(u_1=\ln(\cos x)\), \(u_2=x\).`],['Assemble the particular solution',r`\[y_p=\cos x\ln(\cos x)+x\sin x.\] The domain keeps \(\cos x\) positive and the forcing defined.`]],r`y=C_1\cos x+C_2\sin x+\cos x\ln(\cos x)+x\sin x`,r`For the particular part, \(y_p'=-\sin x\ln(\cos x)+x\cos x\). Differentiating again and adding \(y_p\) leaves \(\sin^2x/\cos x+\cos x=\sec x\).`)
],E('Your turn',r`Use variation of parameters to find a particular solution of \(y''=x\).`,[['Use a simple fundamental pair',r`Choose \(y_1=1\), \(y_2=x\), \(W=1\).`],['Integrate the parameters',r`\[u_1'=-x^2,\quad u_2'=x,\quad u_1=-\frac{x^3}{3},\quad u_2=\frac{x^2}{2}.\]`],['Combine',r`\[y_p=-\frac{x^3}{3}+x\frac{x^2}{2}=\frac{x^3}{6}.\]`]],r`y_p=\frac{x^3}{6}`,r`Two derivatives give \(x\). The general solution adds \(C_1+C_2x\).`),'The formulas use the right side after normalization. Leaving a leading coefficient on y″ changes the answer.');
L('11-cauchy-euler','Cauchy–Euler equations',2,['4.7'],'Use powers of x for equations whose coefficients match the derivative order.','Polynomial roots and logarithmic differentiation.',[
['Spot the powers',r`The homogeneous form is \[ax^2y''+bxy'+cy=0.\] Try \(y=x^m\), not \(e^{mx}\). Substituting gives the indicial equation \[am(m-1)+bm+c=0.\]`],
['Translate the roots on x>0',r`Distinct real roots give \(C_1x^{m_1}+C_2x^{m_2}\). A repeated root \(m\) gives \(x^m(C_1+C_2\ln x)\). Roots \(\alpha\pm i\beta\) give \[x^\alpha[C_1\cos(\beta\ln x)+C_2\sin(\beta\ln x)].\] The point \(x=0\) is singular; solve on an interval that avoids it. Negative-x intervals require appropriate real forms using \(|x|\).`],
['For a nonzero right side',r`The substitution \(t=\ln x\), \(Y(t)=y(e^t)\), gives \(xy'=Y'\) and \(x^2y''=Y''-Y'\). It turns the equation into a constant-coefficient equation in \(t\), including the transformed forcing.`]
],['Identify the Cauchy–Euler pattern.','Substitute x^m and keep m(m−1) for the second derivative.','Solve the indicial polynomial and choose the correct root form.','Apply conditions at a nonzero x and state the interval.'],[
E('Two powers',r`Solve \(x^2y''-2xy'+2y=0\), \(y(1)=3\), \(y'(1)=4\), for \(x>0\).`,[['Find the indicial roots',r`\[m(m-1)-2m+2=m^2-3m+2=(m-1)(m-2).\]`],['Write the solution',r`\(y=C_1x+C_2x^2\), so \(y'=C_1+2C_2x\).`],['Apply conditions',r`\(C_1+C_2=3\), \(C_1+2C_2=4\). Thus \(C_2=1\), \(C_1=2\).`]],r`y=2x+x^2,\qquad x>0`,r`\(x^2(2)-2x(2+2x)+2(2x+x^2)=0\).`)
],E('Your turn',r`Find the general solution of \(x^2y''+xy'=0\) on \(x>0\).`,[['Find the repeated root',r`\(m(m-1)+m=m^2=0\), so zero is a double root.`],['Use the logarithmic companion',r`\(x^0=1\), and the second solution is \(\ln x\).`]],r`y=C_1+C_2\ln x`,r`\(y'=C_2/x\), \(y''=-C_2/x^2\); the two terms cancel.`),'The indicial polynomial starts with m(m−1), not m².');
L('12-motion-circuits','Springs, damping, and circuits',2,['5.1'],'Build a second-order model and connect the solution to physical behaviour.','Second-order constant-coefficient equations and basic units.',[
['Measure displacement from equilibrium',r`For a spring with mass \(m\), damping constant \(c\), spring constant \(k\), and applied force \(F\), \[mx''+cx'+kx=F(t).\] Here \(x\) is displacement from the static equilibrium, so gravity is already balanced. Choose a positive direction and use it consistently in the initial velocity and force.`],
['Read damping from the roots',r`The discriminant \(c^2-4mk\) distinguishes overdamped (positive), critically damped (zero), and underdamped (negative) motion. With \(c=0\), the natural angular frequency is \(\omega_0=\sqrt{k/m}\). For underdamping the oscillation frequency is \(\sqrt{k/m-c^2/(4m^2)}\).`],
['Transient and driven motion',r`In a forced problem, \(x=x_c+x_p\). With positive damping the complementary part decays. Without damping, sinusoidal forcing at the natural frequency leads to a resonant response with a growing factor \(t\). Write \(A\cos\omega t+B\sin\omega t=R\cos(\omega t-\phi)\), with \(R=\sqrt{A^2+B^2}\) and the correct quadrant for \(\phi\).`],
['The electrical analogue',r`For charge \(q\) in a series LRC circuit, \[Lq''+Rq'+\frac{1}{C}q=E(t),\qquad i=q'.\] Inductance \(L\) plays the role of mass, resistance \(R\) of damping, and \(1/C\) of stiffness. Do not confuse capacitance \(C\) with an integration constant.`]
],['Define the dependent variable and sign convention.','Write the physical equation with consistent units.','Solve and apply displacement/charge and velocity/current conditions.','Interpret frequency, amplitude, decay, and long-term behaviour.'],[
E('An undamped spring',r`A 1 kg mass has spring constant 9 N/m and no damping or external force. Initially x=0.1 m and velocity is zero. Find its motion.`,[['Build the IVP',r`\[x''+9x=0,\qquad x(0)=0.1,\quad x'(0)=0.\]`],['Solve the characteristic equation',r`Roots \(\pm3i\) give \(x=A\cos3t+B\sin3t\).`],['Apply the conditions',r`\(A=0.1\) and \(3B=0\). The amplitude is 0.1 m, angular frequency 3 rad/s, and period \(2\pi/3\) s.`]],r`x(t)=0.1\cos3t\ \text{m}`,r`Acceleration is \(-0.9\cos3t\), exactly \(-9x\).`),
E('A critically damped response',r`Solve \(x''+4x'+4x=0\), \(x(0)=1\), \(x'(0)=0\).`,[['Identify the repeated root',r`\((r+2)^2=0\), so \(x=(A+Bt)e^{-2t}\).`],['Differentiate before substituting',r`\[x'=[B-2A-2Bt]e^{-2t}.\] The conditions give \(A=1\) and \(B=2\).`]],r`x(t)=(1+2t)e^{-2t}`,r`For \(t>0\), \(x'=-4te^{-2t}<0\). The displacement returns toward zero without changing sign.`)
],E('Your turn',r`For a circuit with L=1 H, R=0, C=1/4 F, and E=0, find charge and current if q(0)=0 and i(0)=2 A.`,[['Translate the parameters',r`\[q''+4q=0,\qquad q(0)=0,\quad q'(0)=2.\]`],['Solve for charge',r`\(q=A\cos2t+B\sin2t\). The conditions give \(A=0\), \(B=1\).`],['Differentiate for current',r`Current is the derivative of charge, so \(i=2\cos2t\).`]],r`q(t)=\sin2t\ \text{C},\qquad i(t)=2\cos2t\ \text{A}`,r`At zero the charge is 0 C and current is 2 A.`),'A frequency in radians per second is not the same as cycles per second: divide by 2π to obtain cycles per second.');
L('13-series-review','Power series essentials',3,['6.1'],'Read sigma notation, differentiate a series, and line up powers before comparing coefficients.','Polynomials, factorials, and the ratio test.',[
['An infinite polynomial',r`A power series centered at zero is \[y=\sum_{n=0}^{\infty}a_nx^n=a_0+a_1x+a_2x^2+\cdots.\] Inside its radius of convergence you may differentiate and integrate term by term. The coefficients encode derivatives: \(a_n=y^{(n)}(0)/n!\).`],
['Differentiate without losing the starting index',r`\[y'=\sum_{n=1}^{\infty}na_nx^{n-1},\qquad y''=\sum_{n=2}^{\infty}n(n-1)a_nx^{n-2}.\] The constant term vanishes in \(y'\), and both the constant and linear terms vanish in \(y''\).`],
['Reindex to the same power',r`For coefficient matching, rewrite \[y''=\sum_{n=0}^{\infty}(n+2)(n+1)a_{n+2}x^n.\] Changing the index changes the coefficient, the exponent, and the lower bound together.`],
['Know a few anchor series',r`\[e^x=\sum_{n=0}^{\infty}\frac{x^n}{n!},\quad \sin x=\sum_{n=0}^{\infty}\frac{(-1)^nx^{2n+1}}{(2n+1)!},\quad \cos x=\sum_{n=0}^{\infty}\frac{(-1)^nx^{2n}}{(2n)!}.\] These converge for all real \(x\). The geometric series \(\sum x^n=1/(1-x)\) instead requires \(|x|<1\).`]
],['Write a few terms to see what the summation means.','Differentiate or integrate term by term inside the convergence interval.','Reindex every series to matching powers.','Check convergence separately, including endpoints when needed.'],[
E('Reindex a derivative',r`Write \(y'\) using powers \(x^n\) when \(y=\sum_{n=0}^{\infty}a_nx^n\).`,[['Differentiate the original terms',r`\(y'=a_1+2a_2x+3a_3x^2+\cdots\). In summation form the original index starts at 1.`],['Shift the index',r`Set the new index equal to the old index minus 1. The old coefficient \(na_n\) becomes \((n+1)a_{n+1}\).`]],r`y'=\sum_{n=0}^{\infty}(n+1)a_{n+1}x^n`,r`The terms for \(n=0,1,2\) are \(a_1,2a_2x,3a_3x^2\), matching the direct calculation.`)
],E('Your turn',r`Find the first four nonzero terms and radius of convergence of \(\sum_{n=0}^{\infty}x^n/2^n\).`,[['Recognize the geometric ratio',r`The ratio between consecutive terms is \(x/2\).`],['List and sum',r`The terms begin \(1+x/2+x^2/4+x^3/8\). A geometric series converges when \(|x/2|<1\).`]],r`\sum_{n=0}^{\infty}\frac{x^n}{2^n}=\frac{1}{1-x/2},\qquad |x|<2`,r`The radius is 2. At \(x=\pm2\), the terms do not tend to zero, so both endpoints diverge.`),'When reindexing, changing only the exponent gives incorrect coefficients.');
L('14-series-solutions','Solving with a power series',3,['6.2'],'Turn a differential equation into a recurrence that builds the solution one coefficient at a time.','Power series and reindexing.',[
['When to try a series',r`For \(y''+P(x)y'+Q(x)y=0\), a point is ordinary when \(P\) and \(Q\) are analytic there. A power series centered at an ordinary point can represent solutions locally. If the leading coefficient vanishes, normalize and examine the coefficients before assuming an ordinary-point series works.`],
['The recurrence is the engine',r`Substitute \(y=\sum a_nx^n\), write all terms with the same power of \(x\), and set each coefficient to zero. For a second-order equation, \(a_0=y(0)\) and \(a_1=y'(0)\) are the two starting values. The recurrence determines the rest.`],
['A finite series is usually an approximation',r`Keep an ellipsis or a big-O remainder when truncating. A polynomial approximation may satisfy the ODE only to the retained order. Check more than the first two terms to catch index errors.`]
],['Choose the expansion point and check that it is ordinary.','Substitute the series and reindex.','Equate coefficients and solve for the next coefficient.','Use the initial values, then generate several terms.'],[
E('Recover cosine from its equation',r`Solve \(y''+y=0\), \(y(0)=1\), \(y'(0)=0\), using a series.`,[['Substitute matching powers',r`\[\sum_{n=0}^{\infty}\big[(n+2)(n+1)a_{n+2}+a_n\big]x^n=0.\]`],['Form the recurrence',r`\[a_{n+2}=-\frac{a_n}{(n+2)(n+1)}.\] The recurrence links coefficients two places apart.`],['Use the starting values',r`\(a_0=1,a_1=0\). Thus \(a_2=-1/2,a_3=0,a_4=1/24,a_5=0,a_6=-1/720\).`],['Recognize the result',r`The even terms alternate and the odd terms vanish.`]],r`y=1-\frac{x^2}{2!}+\frac{x^4}{4!}-\frac{x^6}{6!}+\cdots=\cos x`,r`Cosine has exactly the required initial value and slope and solves the original equation.`)
],E('Your turn',r`Find the terms through degree 6 for \(y''+xy=0\), \(y(0)=1\), \(y'(0)=0\).`,[['Treat the lowest power separately',r`The coefficient of \(x^0\) gives \(2a_2=0\). For \(n\ge1\), \[(n+2)(n+1)a_{n+2}+a_{n-1}=0.\]`],['Generate the coefficients',r`\(a_0=1,a_1=a_2=0\), then \(a_3=-1/6,a_4=a_5=0,a_6=1/180\). The next nonzero term has degree 9.`]],r`y=1-\frac{x^3}{6}+\frac{x^6}{180}+O(x^9)`,r`The recurrence at \(n=1\) gives \(6a_3+a_0=0\); at \(n=4\), \(30a_6+a_3=0\). Both hold.`),'Multiplying a series by x shifts its lowest power. Handle missing low-degree terms before combining sums.');
L('15-laplace-basics','The Laplace transform',4,['7.1'],'Understand the transform as a new representation of a function and learn the core transform pairs.','Improper integrals and exponential functions.',[
['A function of t becomes a function of s',r`The one-sided Laplace transform is \[F(s)=\mathcal L\{f(t)\}=\int_0^{\infty}e^{-st}f(t)\,dt.\] The integral must converge. For example, exponential growth in \(t\) restricts how large \(s\) must be.`],
['Core pairs',r`\[\mathcal L\{1\}=\frac1s,\quad \mathcal L\{t^n\}=\frac{n!}{s^{n+1}},\quad \mathcal L\{e^{at}\}=\frac1{s-a}.\] The power rule uses a nonnegative integer \(n\). For sine and cosine, \[\mathcal L\{\sin bt\}=\frac{b}{s^2+b^2},\qquad \mathcal L\{\cos bt\}=\frac{s}{s^2+b^2}.\] Use \(s>0\) for the polynomial and trigonometric pairs, and \(s>a\) for \(e^{at}\).`],
['Linearity, not multiplication',r`\(\mathcal L\{af+bg\}=aF+bG\). But the transform of a product is generally not the product of the transforms. Keep \(t\)-domain functions and \(s\)-domain expressions on their correct sides.`]
],['Break a sum into simple terms.','Match each term to a transform pair.','Keep coefficients and factorials.','State a convergence region when asked.'],[
E('Use the definition once',r`Compute \(\mathcal L\{e^{2t}\}\) directly.`,[['Combine the exponentials',r`\[\int_0^{\infty}e^{-st}e^{2t}\,dt=\int_0^{\infty}e^{-(s-2)t}\,dt.\]`],['Check convergence',r`For real \(s>2\), the exponential decays as \(t\to\infty\).`],['Evaluate the improper integral',r`\[\left[-\frac{e^{-(s-2)t}}{s-2}\right]_0^{\infty}=0+\frac1{s-2}.\]`]],r`\mathcal L\{e^{2t}\}=\frac1{s-2},\qquad s>2`,r`The transform is positive for \(s>2\), consistent with integrating a positive function.`)
],E('Your turn',r`Find \(\mathcal L\{3t^2-4\sin2t\}\).`,[['Transform the polynomial term',r`\(\mathcal L\{t^2\}=2!/s^3=2/s^3\), so the first term gives \(6/s^3\).`],['Transform the sine term',r`\(\mathcal L\{\sin2t\}=2/(s^2+4)\). Multiply by \(-4\).`]],r`\frac6{s^3}-\frac8{s^2+4},\qquad s>0`,r`The numerator 2 in the sine transform comes from its frequency.`),'The numerator for sine is its frequency b; the numerator for cosine is s.');
L('16-inverse-laplace','Inverse transforms and initial-value problems',4,['7.2'],'Use algebra and partial fractions to recover a time-domain solution.','Transform pairs, partial fractions, and completing the square.',[
['Undo the transform by matching pairs',r`Before taking an inverse, simplify the rational expression. Use polynomial division if needed, then partial fractions. For a repeated factor \((s-a)^m\), include every power from 1 through \(m\). An irreducible quadratic needs a linear numerator.`],
['Initial conditions enter automatically',r`Writing \(Y=\mathcal L\{y\}\), \[\mathcal L\{y'\}=sY-y(0),\qquad \mathcal L\{y''\}=s^2Y-sy(0)-y'(0).\] Transform the entire equation, solve for \(Y\), and then invert term by term.`],
['Prepare a quadratic for the table',r`Complete the square and rewrite the numerator in terms of the shifted variable. For example, \(s^2-4s+13=(s-2)^2+9\). A numerator \(s-2\) matches shifted cosine; a numerator 3 matches shifted sine.`]
],['Transform derivatives with their initial-value terms.','Collect Y terms and solve for Y.','Decompose into recognizable transform pairs.','Invert and check the initial values in the final time-domain answer.'],[
E('Solve an IVP with Laplace',r`Solve \(y'+2y=1\), \(y(0)=0\).`,[['Transform the equation',r`\[sY+2Y=\frac1s\quad\Rightarrow\quad Y=\frac1{s(s+2)}.\]`],['Find partial fractions',r`\[\frac1{s(s+2)}=\frac A s+\frac B{s+2}.\] Multiplying through gives \(1=A(s+2)+Bs\). At \(s=0\), \(A=1/2\); at \(s=-2\), \(B=-1/2\).`],['Invert each term',r`\(1/s\) corresponds to 1, and \(1/(s+2)\) corresponds to \(e^{-2t}\).`]],r`y(t)=\frac12(1-e^{-2t})`,r`\(y(0)=0\) and \(y'+2y=e^{-2t}+1-e^{-2t}=1\).`)
],E('Your turn',r`Solve \(y''+y=0\), \(y(0)=2\), \(y'(0)=3\), using Laplace transforms.`,[['Transform with both initial terms',r`\[(s^2Y-2s-3)+Y=0.\]`],['Separate the transform',r`\[Y=\frac{2s}{s^2+1}+\frac3{s^2+1}.\]`],['Match cosine and sine',r`The first numerator has \(s\); the second has frequency 1 multiplied by 3.`]],r`y(t)=2\cos t+3\sin t`,r`The value at zero is 2 and the slope at zero is 3.`),'The initial-condition terms are subtracted in the derivative transform. Move them across the equation carefully.');
L('17-shifts-and-steps','Shifts, switches, and piecewise inputs',4,['7.3'],'Distinguish exponential shifts from time delays and write switched inputs correctly.','Basic Laplace transforms and piecewise functions.',[
['An exponential shifts s',r`If \(\mathcal L\{f(t)\}=F(s)\), then \[\mathcal L\{e^{at}f(t)\}=F(s-a).\] Replace every occurrence of \(s\) in the transform, not just the denominator’s first term.`],
['A delay shifts time',r`The unit step \(u(t-a)\) is zero before \(a\) and one after \(a\). The second shifting rule is \[\mathcal L\{u(t-a)f(t-a)\}=e^{-as}F(s),\qquad a\ge0.\] Both the step and the function must use the delayed time \(t-a\).`],
['Rewrite before transforming',r`For \(t\,u(t-2)\), rewrite \(t=(t-2)+2\). Thus \[\mathcal L\{t\,u(t-2)\}=e^{-2s}\left(\frac1{s^2}+\frac2s\right).\] A rectangular input of height \(H\), on from \(a\) to \(b\), is \(H[u(t-a)-u(t-b)]\).`]
],['Decide whether the change is an exponential factor or a time delay.','For a delayed input, rewrite everything inside using t−a.','Apply the appropriate transform rule.','When inverting, delay the entire function and multiply by the step.'],[
E('Switch on a constant input',r`Solve \(y'+y=u(t-2)\), \(y(0)=0\).`,[['Transform the switched forcing',r`\[(s+1)Y=\frac{e^{-2s}}s,\qquad Y=e^{-2s}\frac1{s(s+1)}.\]`],['Invert the undelayed factor',r`\(1/[s(s+1)]=1/s-1/(s+1)\), whose inverse is \(f(t)=1-e^{-t}\).`],['Apply the time delay',r`Replace \(t\) by \(t-2\) in the whole function and multiply by \(u(t-2)\).`]],r`y(t)=u(t-2)\big(1-e^{-(t-2)}\big)`,r`The solution is zero before 2. After 2, \(y'+y=1\); the value is continuous at the switch.`)
],E('Your turn',r`Find \(\mathcal L^{-1}\{e^{-3s}/(s^2+4)\}\).`,[['Match the unshifted sine pair',r`\(1/(s^2+4)\) is the transform of \((1/2)\sin2t\), because the sine pair needs numerator 2.`],['Delay by 3',r`Replace \(t\) by \(t-3\) and turn the result on at 3.`]],r`\frac12u(t-3)\sin\big(2(t-3)\big)`,r`Before \(t=3\) the response is zero. The undelayed shape is scaled by \(1/2\).`),r`The factor \(e^{-as}\) means a time delay, not multiplication of the answer by \(e^{-at}\).`);
L('18-convolution','Convolution and transform operations',4,['7.4'],'Recognize products of transforms and handle time factors without starting a new integral from scratch.','Laplace transforms, derivatives, and definite integration.',[
['A product in s becomes a convolution',r`Define \[(f*g)(t)=\int_0^t f(\tau)g(t-\tau)\,d\tau.\] Then \(\mathcal L\{f*g\}=F(s)G(s)\). The integration variable \(\tau\) is a placeholder; \(t\) stays fixed during the integral.`],
['Time multiplication becomes differentiation',r`\[\mathcal L\{t f(t)\}=-F'(s),\qquad \mathcal L\{t^n f(t)\}=(-1)^nF^{(n)}(s).\] For example, differentiating \(1/(s-a)\) gives \(\mathcal L\{te^{at}\}=1/(s-a)^2\).`],
['Integration in time',r`\[\mathcal L\left\{\int_0^t f(\tau)\,d\tau\right\}=\frac{F(s)}s.\] This is convolution with the constant function 1.`],
['Optional: a repeating input',r`For a piecewise continuous function repeating with period \(T\), \[\mathcal L\{f\}=\frac{\int_0^T e^{-st}f(t)\,dt}{1-e^{-sT}},\qquad s>0.\] The instructor’s periodic-function supplement is marked not tested and intended for electronics students. Learn the main operations above first.`]
],['Factor the transform into recognizable pieces.','Identify the two inverse functions.','Set up the convolution with limits 0 and t.','Integrate, simplify, and compare with partial fractions when possible.'],[
E('Invert a product by convolution',r`Find \(\mathcal L^{-1}\{1/[s(s+1)]\}\) using convolution.`,[['Identify the factors',r`\(1/s\) corresponds to 1 and \(1/(s+1)\) corresponds to \(e^{-t}\).`],['Set up the convolution',r`\[(1*e^{-t})(t)=\int_0^t e^{-(t-\tau)}\,d\tau.\]`],['Integrate',r`Pull out \(e^{-t}\), which is constant with respect to \(\tau\): \[e^{-t}\int_0^t e^\tau\,d\tau=e^{-t}(e^t-1).\]`]],r`1-e^{-t}`,r`Partial fractions give \(1/s-1/(s+1)\), confirming the answer.`)
],E('Your turn',r`Find \(\mathcal L\{t\sin2t\}\).`,[['Start from the known pair',r`\(F(s)=2/(s^2+4)\).`],['Differentiate and negate',r`\[F'(s)=-\frac{4s}{(s^2+4)^2}.\] The time-factor rule takes \(-F'(s)\).`]],r`\mathcal L\{t\sin2t\}=\frac{4s}{(s^2+4)^2}`,r`For large \(s\), the transform behaves like \(4/s^3\), matching \(t\sin2t\approx2t^2\) near zero.`),'In a convolution, g must be evaluated at t−τ. Multiplying f(t)g(t) is a different operation.');
L('19-impulses','Impulse inputs and the Dirac delta',4,['7.5'],'Model a short kick and understand the jump it causes.','Laplace transforms and time shifts.',[
['The delta represents concentrated area',r`The Dirac delta is an idealized impulse rather than an ordinary finite-valued function. An impulse \(J\delta(t-a)\) has total strength \(J\). Its transform is \[\mathcal L\{\delta(t-a)\}=e^{-as},\qquad a>0.\]`],
['What jumps?',r`For \(my''+cy'+ky=J\delta(t-a)\), displacement remains continuous and velocity jumps by \[y'(a^+)-y'(a^-)=\frac Jm.\] Integrate the equation across a tiny interval around \(a\) to obtain this jump. In a first-order equation \(y'+ky=J\delta(t-a)\), it is \(y\) itself that jumps by \(J\).`]
],['Transform the delta into its exponential delay factor.','Solve for the transformed response.','Invert the undelayed part, then delay it.','Check behaviour before the impulse and the correct jump size.'],[
E('Kick an oscillator at t=π',r`Solve \(y''+y=\delta(t-\pi)\), \(y(0)=y'(0)=0\).`,[['Transform the IVP',r`\[(s^2+1)Y=e^{-\pi s},\qquad Y=\frac{e^{-\pi s}}{s^2+1}.\]`],['Use the undelayed inverse',r`\(1/(s^2+1)\) corresponds to \(\sin t\).`],['Delay the response',r`The oscillator remains at rest until the kick, then follows the sine response starting at \(t=\pi\).`]],r`y(t)=u(t-\pi)\sin(t-\pi)`,r`Displacement is zero on both sides of the instant of impact. Velocity changes from 0 to \(\cos0=1\), the required unit jump.`)
],E('Your turn',r`Solve \(y'+2y=3\delta(t-1)\), \(y(0)=0\).`,[['Transform and solve',r`\[(s+2)Y=3e^{-s}\quad\Rightarrow\quad Y=\frac{3e^{-s}}{s+2}.\]`],['Invert and delay',r`The undelayed inverse is \(3e^{-2t}\).`]],r`y(t)=3u(t-1)e^{-2(t-1)}`,r`The value jumps from 0 to 3 at \(t=1\), then decays. Away from the impulse, \(y'+2y=0\).`),'A unit step stays on; a delta is a concentrated impulse. Their transforms differ by a factor of s.');
L('20-linear-systems','Linear systems and eigenvectors',5,['8.1','8.2'],'Solve coupled equations by identifying independent directions of motion.','Matrix multiplication, determinants, and characteristic roots.',[
['Write the matrix form',r`A system such as \(x'=ax+by\), \(y'=cx+dy\) is \[\mathbf X'=A\mathbf X,\qquad \mathbf X=\begin{pmatrix}x\\y\end{pmatrix},\quad A=\begin{pmatrix}a&b\\c&d\end{pmatrix}.\] Each row reproduces one differential equation.`],
['An eigenvector keeps its direction',r`Try \(\mathbf X=e^{\lambda t}\mathbf v\). Substitution gives \(A\mathbf v=\lambda\mathbf v\). Find eigenvalues from \(\det(A-\lambda I)=0\), then a nonzero vector in the nullspace for each eigenvalue.`],
['Combine independent modes',r`Two independent real eigenvectors give \[\mathbf X=C_1e^{\lambda_1t}\mathbf v_1+C_2e^{\lambda_2t}\mathbf v_2.\] Initial values produce a small linear system for \(C_1,C_2\). A negative real eigenvalue gives decay in its mode; a positive one gives growth.`],
['Complex or repeated eigenvalues',r`For \(\lambda=\alpha+i\beta\), \(\mathbf v=\mathbf p+i\mathbf q\), take real and imaginary parts: \(e^{\alpha t}(\mathbf p\cos\beta t-\mathbf q\sin\beta t)\) and \(e^{\alpha t}(\mathbf p\sin\beta t+\mathbf q\cos\beta t)\). If a repeated eigenvalue has only one eigenvector \(\mathbf v\), find \(\mathbf w\) with \((A-\lambda I)\mathbf w=\mathbf v\). A second solution is \(e^{\lambda t}(t\mathbf v+\mathbf w)\).`]
],['Write the coefficient matrix and characteristic determinant.','Find eigenvalues and independent eigenvectors.','Build a real general solution, using generalized vectors if needed.','Apply the initial vector and verify each component equation.'],[
E('Two real modes',r`Solve \(\mathbf X'=\begin{pmatrix}2&1\\1&2\end{pmatrix}\mathbf X\), \(\mathbf X(0)=\begin{pmatrix}2\\0\end{pmatrix}\).`,[['Find eigenvalues',r`\[\det(A-\lambda I)=(2-\lambda)^2-1=(\lambda-3)(\lambda-1).\]`],['Find eigenvectors',r`For \(\lambda=3\), choose \((1,1)^T\). For \(\lambda=1\), choose \((1,-1)^T\). Multiplying by \(A\) confirms both choices.`],['Apply the initial vector',r`\(C_1+C_2=2\), \(C_1-C_2=0\), so \(C_1=C_2=1\).`]],r`x=e^{3t}+e^t,\qquad y=e^{3t}-e^t`,r`\(x'=3e^{3t}+e^t=2x+y\), and \(y'=3e^{3t}-e^t=x+2y\).`),
E('One eigenvector for a repeated eigenvalue',r`Find the general solution for \(A=\begin{pmatrix}1&1\\0&1\end{pmatrix}\).`,[['Find the eigenvector',r`The repeated eigenvalue is 1. The equation \((A-I)\mathbf v=0\) gives \(\mathbf v=(1,0)^T\).`],['Find a generalized eigenvector',r`Choose \(\mathbf w=(0,1)^T\), since \((A-I)\mathbf w=\mathbf v\).`],['Build the two modes',r`Use \(e^t\mathbf v\) and \(e^t(t\mathbf v+\mathbf w)\).`]],r`\mathbf X=C_1e^t\begin{pmatrix}1\\0\end{pmatrix}+C_2e^t\begin{pmatrix}t\\1\end{pmatrix}`,r`For the second mode, differentiating \((te^t,e^t)^T\) gives \(((t+1)e^t,e^t)^T\), exactly its product with \(A\).`)
],E('Your turn',r`Solve \(x'=-y\), \(y'=x\), with \(x(0)=1\), \(y(0)=0\).`,[['Eliminate one variable',r`Differentiating \(x'=-y\) gives \(x''=-y'=-x\). Also \(x'(0)=-y(0)=0\).`],['Recover both components',r`\(x=\cos t\). Then \(y=-x'=\sin t\).`]],r`x=\cos t,\qquad y=\sin t`,r`\(x^2+y^2=1\), so the trajectory is a circle. The eigenvalues are \(\pm i\).`),'An eigenvector must be nonzero. Multiplying it by a nonzero constant changes its representation, not its direction.');
L('21-forced-systems','Nonhomogeneous systems',5,['8.3'],'Combine the system’s natural modes with a response to external forcing.','Linear systems, scalar integrating factors, and matrix inverses.',[
['Add a particular vector solution',r`For \[\mathbf X'=A\mathbf X+\mathbf f(t),\] the general solution is \(\mathbf X=\mathbf X_c+\mathbf X_p\). A simple constant or exponential forcing may allow a vector trial, but resonance can require a factor \(t\).`],
['Variation of parameters for systems',r`Let \(\Phi(t)\) be a fundamental matrix whose columns are independent homogeneous solutions. Setting \(\mathbf X=\Phi\mathbf u\) gives \(\Phi\mathbf u'=\mathbf f\). Therefore \[\mathbf X=\Phi(t)\left[\mathbf c+\int\Phi(t)^{-1}\mathbf f(t)\,dt\right].\] Matrix order matters; multiply \(\Phi^{-1}\) by \(\mathbf f\), not the other way around.`],
['Use the structure when possible',r`If one equation does not depend on the other unknown, solve it first, then substitute into the remaining equation. This is often simpler than computing a fundamental matrix. A scalar second-order equation can also be rewritten as a system using \(X_1=y\), \(X_2=y'\).`]
],['Find the homogeneous solution or identify a triangular structure.','Choose a simple particular trial or use variation of parameters.','Add the two parts and apply the initial vector.','Check both equations, including their forcing terms.'],[
E('A forced triangular system',r`Solve \(x'=x+1\), \(y'=x+y\), with \(x(0)=y(0)=0\).`,[['Solve the independent equation first',r`\(x'-x=1\) gives \(x=Ce^t-1\). The initial value makes \(C=1\), so \(x=e^t-1\).`],['Substitute into the y equation',r`\[y'-y=e^t-1.\] Multiplication by \(e^{-t}\) gives \((e^{-t}y)'=1-e^{-t}\).`],['Integrate and apply the second initial value',r`\[e^{-t}y=t+e^{-t}+C.\] At zero, \(0=1+C\), so \(C=-1\).`]],r`x=e^t-1,\qquad y=(t-1)e^t+1`,r`\(x'=e^t=x+1\) and \(y'=te^t=x+y\). Both initial values are zero.`)
],E('Your turn',r`Solve \(\mathbf X'=\begin{pmatrix}-1&0\\0&-2\end{pmatrix}\mathbf X+\begin{pmatrix}1\\2\end{pmatrix}\), \(\mathbf X(0)=\mathbf0\).`,[['Separate the independent equations',r`\(x'+x=1\), \(y'+2y=2\). Each has the constant equilibrium 1.`],['Apply zero initial conditions',r`The general forms are \(x=1+C_1e^{-t}\), \(y=1+C_2e^{-2t}\). Both constants are \(-1\).`]],r`\mathbf X=\begin{pmatrix}1-e^{-t}\\1-e^{-2t}\end{pmatrix}`,r`Both components approach 1. Substitution gives \(x'+x=1\) and \(y'+2y=2\).`),'The particular solution is a vector: it must satisfy every component equation simultaneously.');
const units=[{id:1,title:'First-order equations',description:'Start with the language, then learn how to recognize and solve each main equation type.'},{id:2,title:'Higher-order equations and models',description:'Build complete solutions and use them for motion, forcing, and circuits.'},{id:3,title:'Power series',description:'Find a solution coefficient by coefficient when elementary methods are less convenient.'},{id:4,title:'Laplace transforms',description:'Turn initial-value problems, switched inputs, and impulses into algebra.'},{id:5,title:'Systems of equations',description:'Use matrices and independent modes to solve coupled problems.'}];
module.exports={lessons,units};
