const r=String.raw;
const units=[];
function unit(slug,title,weeks,chapter,sections,example,practice,answer){units.push({slug,title,weeks,chapter,sections,example,practice,answer});}
unit('charge-and-force','Charge and Coulomb’s law','1–2','21.1–21.4',[
['What charge means',r`Charge is a signed property measured in coulombs (C). Electrons have charge $-e$ and protons $+e$, where $e=1.602\times10^{-19}\,\mathrm C$. Charge is conserved: rubbing transfers charge rather than creating it. In a conductor, some charges move easily; in an insulator they remain localized. Grounding allows charge to move to or from Earth.`],
['Calculate one interaction',r`For stationary point charges $q_1,q_2$ separated by distance $r$, $$F=k\frac{|q_1q_2|}{r^2},\qquad k=8.99\times10^9\,\mathrm{N\,m^2/C^2}.$$ This is a magnitude. Draw attraction for opposite signs and repulsion for matching signs. Convert centimetres to metres and microcoulombs to coulombs before substituting.`],
['Add several forces',r`For each source, draw its force on the target charge. Choose axes, calculate each magnitude, resolve it with sine and cosine, then add $F_x$ and $F_y$ separately. Finally $F=\sqrt{F_x^2+F_y^2}$; determine direction from the signed components. Do not add magnitudes unless forces point in the same direction.`]
],['Given / Find','Two +1.00 µC charges are 0.100 m apart. Find the force on either charge.',r`Identify: equal signs repel. Set up: $F=kq^2/r^2$. Execute: $F=(8.99\times10^9)(10^{-6})^2/0.100^2=0.899\,\mathrm N$. Evaluate: each force has this magnitude, with opposite directions; doubling separation gives 0.225 N.`], 'If one charge reverses sign, what changes?', 'The magnitude stays 0.899 N; the interaction becomes attractive.');
unit('fields-and-dipoles','Electric fields, motion, and dipoles','2–3','21.4–21.7',[
['Separate the source from the test charge',r`The field is force per unit positive test charge: $\vec E=\vec F/q$. For source charge $Q$, $E=k|Q|/r^2$ (N/C), outward from positive Q and inward toward negative Q. A test charge q then feels $\vec F=q\vec E$. Negative q reverses the force direction. Superposition means adding field vectors before multiplying by q.`],
['Motion and equilibrium',r`In a uniform field, $\vec a=q\vec E/m$, where m is particle mass. Split motion into axes; the axis with no force has constant velocity. If a charged object hangs at rest, draw tension, weight, and electric force and apply $\sum F_x=\sum F_y=0$. Field lines indicate the direction of force on positive charge; closer spacing means a stronger field. Lines never cross.`],
['Dipoles',r`A dipole contains charges $+q$ and $-q$ separated by vector $\vec d$ from negative to positive. Its dipole moment is $\vec p=q\vec d$ (C m). In uniform E the net force is zero, but the torque is $\vec\tau=\vec p\times\vec E$, magnitude $pE\sin\theta$. Its potential energy is $U=-pE\cos\theta$. Here θ is between p and E. Parallel alignment is stable. In nonuniform fields a dipole may also experience net force.`]
],['Given / Find','A proton is in a uniform field of 200 N/C to the right. Find its acceleration; e = 1.602 × 10⁻¹⁹ C and mₚ = 1.673 × 10⁻²⁷ kg.',r`Identify: the proton is positive, so force is rightward. Set up: $a=eE/m_p$. Execute: $a=1.92\times10^{10}\,\mathrm{m/s^2}$ to the right. Evaluate: using an electron reverses direction and increases acceleration magnitude because its mass is smaller.`],'At what dipole angle is torque largest?',r`At 90°, because $\sin\theta=1$. Torque vanishes at both 0° and 180°, but 180° is unstable.`);
unit('continuous-fields','Fields from continuous charge','2–3','21.5',[
['Replace a sum with an integral',r`Choose a source coordinate and a small charge $dq$. For a line, $dq=\lambda\,ds$; for a surface, $dq=\sigma\,dA$; for a volume, $dq=\rho\,dV$. The densities have units C/m, C/m², and C/m³. If density varies, keep that dependence inside the integral. Calculate $d\vec E=k\,dq\,\hat{\mathbf r}/r^2$, then integrate components, with r the source-to-observation distance.`],
['Let symmetry remove components',r`For a uniformly charged ring of radius a and total charge Q, observed distance x along its axis, sideways components cancel in opposite pairs. Every piece is distance $\sqrt{x^2+a^2}$ away. Projection gives $$E_x=\frac{kQx}{(x^2+a^2)^{3/2}}.$$ The sign includes the signs of Q and x. The field at the centre is zero, even though the electric potential need not be zero.`],
['Build a disk from rings',r`A disk of radius R and uniform surface density σ contains rings with $dq=\sigma(2\pi s\,ds)$. On its positive axis at x > 0, $$E_x=\frac{\sigma}{2\varepsilon_0}\left(1-\frac{x}{\sqrt{x^2+R^2}}\right).$$ Here s is the ring integration radius and $\varepsilon_0=8.854\times10^{-12}\,\mathrm{C^2/(N\,m^2)}$. Near a large disk this approaches the infinite-sheet field; far away use total charge $Q=\sigma\pi R^2$ to recover $kQ/x^2$.`]
],['Given / Find','A ring has Q = +1.00 µC and a = 0.100 m. Find the field x = 0.100 m along its axis.',r`Identify: use ring symmetry. Set up: only axial components survive. Execute: $E_x=kQx/(x^2+a^2)^{3/2}=3.18\times10^5\,\mathrm{N/C}$. Evaluate: it points away from the positive ring; the formula gives zero at x = 0.`],'What changes if a uniform ring has negative charge?', 'Every field vector reverses. The magnitude is unchanged for the same |Q|.');
unit('gauss-and-conductors','Flux, Gauss’s law, and conductors','3–5','22.1–22.5',[
['Flux measures field crossing a surface',r`For a flat area A in a uniform field, $\Phi_E=EA\cos\theta$, where θ is between the field and the area normal, not the surface itself. Generalize to $\Phi_E=\int\vec E\cdot d\vec A$. For a closed surface use outward normals. Positive flux is outward; negative is inward.`],
['Use Gauss only after checking symmetry',r`$$\oint\vec E\cdot d\vec A=Q_{enc}/\varepsilon_0.$$ The law always holds, but solving for E easily requires symmetry. A centred spherical surface gives $E4\pi r^2=Q_{enc}/\varepsilon_0$. A coaxial cylinder of radius r and length ℓ around an infinite uniform line gives $E2\pi r\ell=\lambda\ell/\varepsilon_0$, or $E=\lambda/(2\pi\varepsilon_0r)$. A pillbox through an infinite insulating sheet gives $2EA=\sigma A/\varepsilon_0$, or $E=\sigma/(2\varepsilon_0)$.`],
['Inside matter and conductors',r`For a uniformly charged solid sphere of radius R and total Q, at r < R the enclosed charge is $Q(r/R)^3$, so $E=kQr/R^3$ radially (signed Q). Outside, $E=kQ/r^2$. In electrostatic equilibrium a conductor has E = 0 in its material, constant potential, and excess charge on surfaces. Just outside, the normal field is $E_n=\sigma/\varepsilon_0$. A charge q in an empty internal cavity induces −q on its inner conductor surface.`]
],['Given / Find','A sphere encloses +3.00 nC. Find its outward flux and the field at r = 0.200 m if the distribution is spherically symmetric and entirely inside that radius.',r`Identify: flux depends on enclosed charge. Set up: $\Phi_E=Q/\varepsilon_0$ and $E=\Phi_E/(4\pi r^2)$. Execute: $\Phi_E=339\,\mathrm{N\,m^2/C}$ and $E=674\,\mathrm{N/C}$ outward. Evaluate: doubling radius leaves flux fixed but quarters E.`],'Can zero enclosed charge prove zero field everywhere on the surface?', 'No. It proves zero net flux. External charges can produce nonzero fields whose inward and outward fluxes cancel.');
unit('potential','Electric potential and energy','5–7','23.1–23.5',[
['Potential is energy per charge',r`Potential V is measured in volts (J/C); potential energy U is in joules. A charge q has change $\Delta U=q\Delta V$, and electric work is $W=-\Delta U$. With no other work, $\Delta K=-q\Delta V$. Negative charges can gain kinetic energy while moving to higher potential.`],
['Calculate V before differentiating',r`Taking V = 0 at infinity for localized charges, a point source has $V=kQ/r$. Potentials add as signed scalars: $V=\sum_i kQ_i/r_i$. For continuous charge use $V=\int k\,dq/r$. For a spherical conductor of radius R, V is $kQ/R$ throughout its interior and $kQ/r$ outside. Infinite lines and sheets require a finite reference potential rather than zero at infinity.`],
['Connect field and equipotentials',r`$$V_b-V_a=-\int_a^b\vec E\cdot d\vec\ell,\qquad\vec E=-\nabla V.$$ In one dimension $E_x=-dV/dx$. Field points toward decreasing V, perpendicular to equipotential surfaces. A line with density λ gives $V_b-V_a=-\lambda\ln(r_b/r_a)/(2\pi\varepsilon_0)$. A uniform field gives $\Delta V=-\vec E\cdot\Delta\vec r$. Keep a reference and direction consistent.`]
],['Given / Find','A +2.00 µC source is 0.300 m from P. Find V(P), taking zero at infinity, and U for a −1.00 nC test charge at P.',r`Identify: potential is a scalar. Set up: $V=kQ/r$, $U=qV$. Execute: $V=5.99\times10^4\,\mathrm V$ and $U=-5.99\times10^{-5}\,\mathrm J$. Evaluate: negative U is consistent with attraction and the chosen zero at infinite separation.`],'If V(x) = A x², what is Eₓ?',r`$E_x=-2Ax$. Here A has units V/m², so Eₓ has units V/m.`);
unit('capacitors','Capacitance, combinations, and dielectrics','7–9','24.1–24.4',[
['Define capacitance from geometry',r`Capacitance $C=Q/\Delta V$ (farads, F) uses the positive charge magnitude Q on one plate and voltage magnitude between plates. For parallel plates, $C=\varepsilon A/d$ neglecting edges; A is overlap area and d is separation. For concentric spherical conductors with radii a < b, $C=4\pi\varepsilon ab/(b-a)$. For long coaxial cylinders of length ℓ and radii a < b, $C=2\pi\varepsilon\ell/\ln(b/a)$. Here $\varepsilon=\kappa\varepsilon_0$ for a fully filling linear dielectric.`],
['Identify what the connection shares',r`Parallel capacitors share voltage: $C_{eq}=\sum C_i$. Series capacitors have equal charge magnitudes when intermediate nodes are initially neutral: $1/C_{eq}=\sum 1/C_i$. Replace one combination at a time, then work backwards using $Q_i=C_iV_i$. Series equivalent capacitance must be smaller than any individual value.`],
['Energy and dielectric conditions',r`$$U=\tfrac12 CV^2=\frac{Q^2}{2C}=\tfrac12 QV.$$ Field energy density is $u=\frac12\varepsilon E^2$. A dielectric polarizes and increases C. With a battery attached V remains fixed, so Q increases. With the battery disconnected Q remains fixed, so V decreases. Choose the correct fixed quantity before using an energy formula.`]
],['Given / Find','Capacitors of 2.00 µF and 4.00 µF are in series across 12.0 V. Find equivalent capacitance, each charge, and each voltage.',r`Identify: series means common charge magnitude. Set up: $C_{eq}=(1/2+1/4)^{-1}=1.33\,\mathrm{\mu F}$. Execute: $Q=C_{eq}V=16.0\,\mathrm{\mu C}$, $V_1=Q/C_1=8.00\,\mathrm V$, $V_2=4.00\,\mathrm V$. Evaluate: voltages add to 12.0 V; the smaller capacitor has the larger voltage.`],'What is their equivalent capacitance if connected in parallel?', '6.00 µF. Both see the same voltage, and their charges add.');
unit('dc-networks','Current, resistance, and Kirchhoff’s laws','8–9','25.1–25.5; 26.1–26.2',[
['Connect motion to current',r`Current $I=dQ/dt$ is measured in amperes (C/s); conventional current follows positive charge flow. For uniform current density, $J=I/A=n|q|v_d$, where n is mobile-carrier number per volume and v_d is drift-speed magnitude. Ohmic material obeys $\vec E=\rho\vec J$. A uniform wire has $R=\rho\ell/A$, with resistivity ρ in Ω m. Near a reference temperature $R=R_0[1+\alpha(T-T_0)]$.`],
['Reduce networks and track power',r`Ohm’s law is $V=IR$ for an ohmic resistor. Series resistances add; parallel conductances add: $1/R_{eq}=\sum 1/R_i$. Resistor power is $P=IV=I^2R=V^2/R$. A source with emf $\mathcal E$ and internal resistance r has terminal voltage $V=\mathcal E-Ir$ while delivering current.`],
['Write equations for unreducible networks',r`Choose branch-current directions; guesses may later be negative. At each independent junction, sum incoming current = sum outgoing current. Around each independent loop, sum potential changes = 0. Crossing a resistor with its current is −IR; against current is +IR. Crossing an ideal source from − to + is $+\mathcal E$. Solve the simultaneous equations and check power delivered equals power absorbed.`]
],['Given / Find','A 12.0 V ideal source drives 2.00 Ω and 4.00 Ω in series. Find current and resistor powers.',r`Identify: one current path. Set up: $R_{eq}=6.00\,\Omega$, $I=V/R_{eq}$. Execute: $I=2.00\,\mathrm A$, $P_1=8.00\,\mathrm W$, $P_2=16.0\,\mathrm W$. Evaluate: the total 24.0 W equals source power VI.`],'If the two resistors are instead parallel across 12.0 V, find total current.', '6.00 A + 3.00 A = 9.00 A. The equivalent resistance is 1.33 Ω.');
unit('rc-circuits','RC charging and discharging','9–10','26.4',[
['Use the time constant',r`A resistor R and capacitor C have time constant $\tau=RC$ (seconds). Capacitor voltage cannot change instantaneously under finite current. When initially uncharged and connected in series to ideal emf $\mathcal E$, $$q(t)=C\mathcal E(1-e^{-t/RC}),\quad I(t)=\frac{\mathcal E}{R}e^{-t/RC}.$$ Here t is elapsed time after switching.`],
['Discharge and general starting states',r`For discharge from initial charge Q₀ through R, $q(t)=Q_0e^{-t/RC}$. If positive current is defined as flowing onto the initially positive capacitor plate, $I=dq/dt=-Q_0e^{-t/RC}/(RC)$. The negative sign shows discharge. More generally, $V_C(t)=V_f+(V_i-V_f)e^{-t/\tau}$, where V_i and V_f are initial and final capacitor voltages.`],
['Check limits before calculating',r`At t = 0, the initially uncharged capacitor has zero voltage. As t approaches infinity during DC charging, I tends to zero and V_C tends to the source voltage. At one time constant it has completed 63.2% of the change; after five it has completed about 99.3%. In a larger network R is the resistance seen by the capacitor with independent sources deactivated.`]
],['Given / Find','R = 10.0 kΩ, C = 100 µF, source = 12.0 V, initially uncharged. Find capacitor voltage and current at t = 1.00 s.',r`Identify: charging. Set up: $\tau=(10^4)(100\times10^{-6})=1.00\,\mathrm s$. Execute: $V_C=12(1-e^{-1})=7.59\,\mathrm V$; $I=(12/10^4)e^{-1}=0.441\,\mathrm{mA}$. Evaluate: resistor drop is 4.41 V and the two drops sum to 12.0 V.`],'How long does a discharging capacitor take to reach half its initial voltage?',r`Solve $1/2=e^{-t/\tau}$: $t=\tau\ln2=0.693\tau$.`);
unit('magnetic-forces','Magnetic fields and forces','10–11','27.1–27.7',[
['A field acts on moving charges',r`$$\vec F_B=q\vec v\times\vec B,\qquad F_B=|q|vB\sin\theta.$$ B is in teslas (T), v is particle velocity, and θ is the angle between v and B. Point right-hand fingers along v and curl toward B to obtain force for positive q; reverse for negative q. Magnetic force is perpendicular to velocity, so it does no work on a point charge. Dots represent out of the page and crosses into it.`],
['Circular motion and flux',r`For velocity perpendicular to a uniform field, $|q|vB=mv^2/r$, so $r=mv/(|q|B)$ and period $T=2\pi m/(|q|B)$. A parallel velocity component produces helical motion instead. Magnetic flux is $\Phi_B=\int\vec B\cdot d\vec A$ in webers (Wb). It uses the angle with the surface normal.`],
['Wires, loops, and torque',r`A straight wire segment has $\vec F=I\vec\ell\times\vec B$, where ℓ points with conventional current. For a curved wire, integrate $I\,d\vec\ell\times\vec B$. A planar N-turn loop has magnetic moment $\vec\mu=NI\vec A$ and torque $\vec\tau=\vec\mu\times\vec B$; its energy is $U=-\vec\mu\cdot\vec B$. The area direction follows a right-hand curl along current.`]
],['Given / Find','A proton moves right at 1.00 × 10⁶ m/s in a 0.200 T field into the page. Find force and orbit radius; mₚ = 1.673 × 10⁻²⁷ kg.',r`Identify: velocity and field are perpendicular. Set up: $F=evB$, $r=m_pv/(eB)$. Execute: $F=3.20\times10^{-14}\,\mathrm N$ upward; $r=0.0522\,\mathrm m$. Evaluate: speed stays constant while direction changes.`],'What is the force if velocity is parallel to B?', 'Zero, because sin 0° = 0.');
unit('magnetic-sources','Biot–Savart and Ampère’s law','11–12','28.1–28.7',[
['Build a magnetic field from current',r`The Biot–Savart law for a steady current element is $$d\vec B=\frac{\mu_0}{4\pi}\frac{I\,d\vec\ell\times\hat{\mathbf r}}{r^2}.$$ Here r points from source element to observation point, I is current, and $\mu_0\approx4\pi\times10^{-7}\,\mathrm{T\,m/A}$. Find direction before integrating. A long straight wire gives $B=\mu_0I/(2\pi r)$; field circles the wire following the right-hand rule.`],
['Loops and parallel wires',r`For a circular loop of radius a on its axis at coordinate x, $B_x=\mu_0Ia^2/[2(a^2+x^2)^{3/2}]$ with sign set by current direction. At the centre, $B=\mu_0I/(2a)$; N identical turns multiply this by N. Two long parallel wires separated by d exert force per length $F/\ell=\mu_0I_1I_2/(2\pi d)$. Same-direction currents attract; opposite currents repel.`],
['Choose an Amperian path',r`For steady currents, $\oint\vec B\cdot d\vec\ell=\mu_0I_{enc}$. Symmetry must make the integral usable: along a circle around a long wire, B is constant and tangent. In a long solenoid, $B\approx\mu_0nI$ inside and small outside, where n is turns per metre. Inside a toroid, $B(r)=\mu_0NI/(2\pi r)$. Ampère’s law remains true when symmetry is insufficient to solve for B this way.`]
],['Given / Find','A long wire carries 5.00 A upward. Find B at a point 0.0200 m to its right.',r`Identify: long straight wire. Set up: $B=\mu_0I/(2\pi r)$. Execute: $B=5.00\times10^{-5}\,\mathrm T$, into the page. Evaluate: doubling distance halves the field, not quarters it.`],'What is the field inside a long air-core solenoid with n = 1000 m⁻¹ and I = 2.00 A?',r`$B=\mu_0nI=2.51\times10^{-3}\,\mathrm T$.`);
unit('induction','Faraday’s law, Lenz’s law, and motional emf','12–13','29.1–29.5',[
['Start with changing flux',r`An N-turn coil has induced emf $$\mathcal E=-N\frac{d\Phi_B}{dt},\qquad\Phi_B=\int\vec B\cdot d\vec A.$$ A change in field, area, or orientation may change flux. Emf is in volts; it exists even if an open circuit prevents current. For a uniform B and flat coil, $\Phi_B=BA\cos\theta$, with θ measured from the area normal.`],
['Find direction separately',r`Choose a surface normal and its right-hand positive loop direction. Lenz’s law says the induced current’s field opposes the change in flux, not necessarily the existing field. If outward flux is increasing, induced field is inward, giving clockwise current. If outward flux is decreasing, induced field is outward, giving counterclockwise current.`],
['Moving conductors and induced fields',r`A conducting rod of length ℓ moving perpendicular to itself and uniform B has emf magnitude $B\ell v$. Direction follows $q\vec v\times\vec B$ on positive charges. In a closed resistive circuit use $I=\mathcal E/R$. A changing magnetic field can also produce a circulating electric field in empty space: $\oint\vec E\cdot d\vec\ell=-d\Phi_B/dt$. This induced field is not described globally by a single-valued electrostatic potential.`]
],['Given / Find','A 100-turn coil of area 0.0100 m² has outward perpendicular B increasing from 0.100 to 0.300 T in 0.200 s. Find emf magnitude and induced current direction.',r`Identify: flux increases outward. Set up: $|\mathcal E|=NA|\Delta B/\Delta t|$. Execute: $|\mathcal E|=1.00\,\mathrm V$. Evaluate: the induced field is inward, so current is clockwise as viewed with outward normal toward you.`],'What if the same outward field decreases instead?', 'The induced field is outward to oppose the decrease, so the current is counterclockwise.');
unit('inductance-maxwell','Inductance, LR circuits, and Maxwell’s equations','13–14','30.1–30.4; 29.7',[
['Inductance stores magnetic energy',r`For a linear coil, flux linkage is $N\Phi_B=LI$, defining self-inductance L in henries (H). Its emf is $\mathcal E_L=-L\,dI/dt$. A long air-core solenoid has $L=\mu_0N^2A/\ell$, where N is turn count, A cross-section, and ℓ length. Stored energy is $U=\tfrac12 LI^2$ and vacuum magnetic energy density is $u_B=B^2/(2\mu_0)$. Mutual inductance M gives emf in a second coil proportional to $-M\,dI_1/dt$, with polarity determined by winding orientation.`],
['Solve an LR transient',r`Inductor current cannot change instantly under finite voltage. For series R, L and ideal emf $\mathcal E$ switched on at zero current, $$I(t)=\frac{\mathcal E}{R}(1-e^{-t/\tau}),\qquad\tau=L/R.$$ During decay through R, $I=I_0e^{-t/\tau}$. At long times under DC, an ideal inductor has zero voltage but may carry nonzero current.`],
['The four field laws',r`$$\oint\vec E\cdot d\vec A=Q_{enc}/\varepsilon_0,\qquad\oint\vec B\cdot d\vec A=0,$$ $$\oint\vec E\cdot d\vec\ell=-\frac{d\Phi_B}{dt},\qquad\oint\vec B\cdot d\vec\ell=\mu_0I_{enc}+\mu_0\varepsilon_0\frac{d\Phi_E}{dt}.$$ The first two integrals are over closed surfaces; the last two over closed loops with consistently oriented spanning surfaces. Q_enc is enclosed charge, I_enc conduction current, and Φ_E and Φ_B are electric and magnetic fluxes. Maxwell’s displacement-current term $I_d=\varepsilon_0\,d\Phi_E/dt$ makes the last law consistent for a charging capacitor even across its gap.`]
],['Given / Find','An ideal 12.0 V source is switched onto R = 6.00 Ω and L = 3.00 H with initial current zero. Find current and stored energy at t = 0.500 s.',r`Identify: LR growth. Set up: $\tau=L/R=0.500\,\mathrm s$ and $I_\infty=\mathcal E/R=2.00\,\mathrm A$. Execute: $I=2(1-e^{-1})=1.26\,\mathrm A$; $U=\tfrac12 LI^2=2.40\,\mathrm J$. Evaluate: current is 63.2% of its final value at one time constant.`],'What happens to displacement current when capacitor voltage stops changing?', 'Electric flux stops changing, so displacement current is zero.');
unit('lab-skills','Lab skills: uncertainty, graphs, and reports','1–14','Course lab manual',[
['Write measurements honestly',r`Record a value, units, and its uncertainty, such as $(12.4\pm0.1)\,\mathrm{cm}$. Distinguish instrument resolution, random scatter, and systematic offsets. Repeat readings to characterize scatter; repeated readings do not automatically remove calibration bias. Preserve raw measurements and convert units in a separate calculation.`],
['Propagate uncertainty under stated assumptions',r`For independent small random uncertainties in $f(x_1,\ldots,x_n)$, $$u_f=\sqrt{\sum_i\left(\frac{\partial f}{\partial x_i}u_i\right)^2}.$$ Here u_i is the standard uncertainty of x_i. For a product or quotient, relative uncertainties combine in quadrature under these assumptions. A worst-case bound instead adds absolute contributions. Use the convention specified by your lab handout; these answer different questions.`],
['Use graphs to test a model',r`Put units on both axes, choose a model, and determine slope and intercept with their units. For V versus I in an ohmic resistor, slope is R in V/A = Ω. Discuss residuals and uncertainty, not just whether a line looks straight. A report should connect the objective, apparatus and procedure, raw observations, analysis, and conclusion. Explain whether results support the model within uncertainty, and identify specific error mechanisms.`]
],['Given / Find','Independent measurements are V = 10.0 ± 0.1 V and I = 2.00 ± 0.02 A, with standard uncertainties. Estimate R and u_R.',r`Identify: $R=V/I$. Set up: $(u_R/R)^2=(u_V/V)^2+(u_I/I)^2$. Execute: $R=5.00\,\Omega$ and $u_R=5\sqrt{0.01^2+0.01^2}=0.071\,\Omega$. Report $(5.00\pm0.07)\,\Omega$. Evaluate: the result assumes independent uncertainties; a worst-case bound would be 0.10 Ω.`],'What are the units of the slope of a graph of current versus voltage?', 'A/V, equivalent to siemens (S). That slope is conductance, 1/R, for an ohmic resistor.');
module.exports=units;
