'use strict';
const bank=window.SETUP_QUESTIONS,byId=new Map(bank.map(q=>[q.id,q])),key='tesselate-math252-identify-v1';
const $=id=>document.getElementById(id);let state=null;
function shuffled(xs){const a=[...xs];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{}}
function show(id){for(const x of ['start','play','finish'])$(x).hidden=x!==id;}
function math(el,tex){katex.render(tex,el,{throwOnError:true,strict:'ignore'});}
function begin(ids){state={ids:shuffled(ids),index:0,answers:{},orders:{}};for(const id of ids)state.orders[id]=shuffled([0,1,2]);save();render(true);}
function render(focus=false){show('play');const q=byId.get(state.ids[state.index]),answer=state.answers[q.id],done=Number.isInteger(answer);$('position').textContent=`Example ${state.index+1} of ${state.ids.length}`;$('score').textContent=`${Object.keys(state.answers).length} answered`;$('progress').max=state.ids.length;$('progress').value=Object.keys(state.answers).length;math($('equation'),q.equation);$('options').replaceChildren();
 state.orders[q.id].forEach((oi,i)=>{const b=document.createElement('button');b.className='option';b.type='button';const letter=document.createElement('span');letter.className='letter';letter.textContent='ABC'[i];const content=document.createElement('span');content.className='choice';const raw=q.options[oi],label=raw.match(/^([A-Za-z][A-Za-z /-]+):\s*/);if(label){const title=document.createElement('span');title.className='label';title.textContent=label[1];const formula=document.createElement('span');math(formula,raw.slice(label[0].length));content.append(title,formula);}else math(content,raw);b.append(letter,content);if(done){b.disabled=true;if(oi===0){b.classList.add('correct');b.append(document.createTextNode(' ✓'));}else if(oi===answer){b.classList.add('wrong');b.append(document.createTextNode(' ✕'));}}b.onclick=()=>{state.answers[q.id]=oi;save();render();};$('options').append(b);});
 $('feedback').replaceChildren();if(done){const title=document.createElement('strong');title.textContent=answer===0?'Correct — '+q.topic:'Use this setup — '+q.topic;const why=document.createElement('p');why.textContent=q.why;const source=document.createElement('a');source.href=q.url;source.target='_blank';source.rel='noopener';source.textContent=q.source+' ↗';$('feedback').append(title,why,source);if(q.recommended){const rec=document.createElement('a');rec.href='https://sites.google.com/site/cazelais/home/math252/homework';rec.target='_blank';rec.rel='noopener';rec.textContent=q.recommended+' · instructor’s recommended list ↗';$('feedback').append(rec);}if(q.homework||q.textbook){const note=document.createElement('a');note.href=q.notes;note.target='_blank';note.rel='noopener';note.textContent='Related lecture notes ↗';$('feedback').append(note);}}
 $('back').disabled=state.index===0;$('next').disabled=!done;$('next').textContent=state.index===state.ids.length-1?'See results →':'Next →';if(focus)$('question').focus();}
function results(){show('finish');const answered=state.ids.filter(id=>Number.isInteger(state.answers[id])),missed=answered.filter(id=>state.answers[id]!==0),unanswered=state.ids.filter(id=>!Number.isInteger(state.answers[id]));$('result').textContent=`${answered.length-missed.length} correct first choices out of ${answered.length} answered. ${unanswered.length?unanswered.length+' still unanswered.':'Round complete.'}`;$('topics').replaceChildren();for(const topic of new Set(answered.map(id=>byId.get(id).topic))){const ids=answered.filter(id=>byId.get(id).topic===topic);const p=document.createElement('p');p.textContent=`${topic}: ${ids.filter(id=>state.answers[id]===0).length}/${ids.length} correct`; $('topics').append(p);}$('retry').disabled=!missed.length;$('retry').onclick=()=>begin(missed);$('continue').hidden=!unanswered.length;$('continue').onclick=()=>{state.index=state.ids.indexOf(unanswered[0]);save();render(true);};$('result-title').focus();}
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{const mode=b.dataset.mode;let pool=bank.filter(q=>mode==='homework'?q.homework:mode==='notes'?!q.homework&&!q.textbook:mode==='recommended'?!!q.recommended:true);if(mode==='quick'){const topics=[...new Set(bank.map(q=>q.topic))];pool=topics.map(t=>shuffled(bank.filter(q=>q.topic===t))[0]);pool.push(...shuffled(bank.filter(q=>!pool.includes(q))).slice(0,10-pool.length));}begin(pool.map(q=>q.id));};
$('next').onclick=()=>{if(state.index===state.ids.length-1)return results();state.index++;save();render(true);};$('back').onclick=()=>{state.index--;save();render(true);};$('end').onclick=results;$('new').onclick=()=>show('start');
try{const s=JSON.parse(localStorage.getItem(key));if(s&&Array.isArray(s.ids)&&s.ids.length&&new Set(s.ids).size===s.ids.length&&s.ids.every(id=>byId.has(id)&&Array.isArray(s.orders?.[id])&&[...s.orders[id]].sort().join(',')==='0,1,2')&&Number.isInteger(s.index)&&s.index>=0&&s.index<s.ids.length&&s.answers&&Object.entries(s.answers).every(([id,a])=>s.ids.includes(id)&&Number.isInteger(a)&&a>=0&&a<3)){state=s;render();}}catch{state=null;show('start');}
